### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by hallojoe** [kjac/FormEditor#1]
NuGet package is missing these files:

- \App_Plugins\FormEditor\js\form.js
- \App_Plugins\FormEditor\editor\form.html

**Comment by kjac** [comment]
Looks like you're right. Pull them from the 0.9.0.2 release zip for now - I'll fix the NuGet package later today.

**Comment by hallojoe** [comment]
Cool, looking forward to see where this project is going :)

**Comment by kjac** [comment]
You'll need to grab \App_Plugins\FormEditor\editor\data.html from the zip as well. 

Looks like everything that's being concatinated by Grunt is left out of the NuGet package. Probably a task order issue - I'll fix it as soon as possible and upload new NuGet packages.

**Comment by kjac** [comment]
New NuGet packages with the missing files have been published (and a new release created) - 0.9.0.3.

**Comment by kjac** [comment]
@hallojoe thanks for reporting the issue :+1:
