### ISSUE TITLE
Localize field names

### ISSUE THREAD

**Issue by ragivi** [kjac/FormEditor#107]
Hi,

I'm trying to localize field names with Umbraco Dictionary Items, but I'm not able to do it. Is this possible?

Regards.

**Comment by kjac** [comment]
Hi @ragivi ,

You should be able to localize your field names by using the built-in localization in Form Editor. 

Check these docs: https://github.com/kjac/FormEditor/blob/master/Docs/extend_field_simple.md#step-2-register-the-field

Basically you need to add your field name to the appropriate localization JS file under */App_Plugins/FormEditor/js/langs/*, using `composition.field.[field alias]` as key. Check the list of Danish field name translations in the Danish localization file - e.g. https://github.com/kjac/FormEditor/blob/master/Source/Umbraco/Plugin/js/langs/da-dk.js#L4

**Comment by ragivi** [comment]
Hi @kjac ,

These docs show the case when you want to localize field type names or other configurations, but I want that the labels of the fields were localized, sorry if I hadn't explained well.

For example: I have a form with a field of textbox type with a label "Name". Then, I want that in the public web, the label "Name" appears localized in English ("Name") and in Spanish ("Nombre").

Thanks!

**Comment by kjac** [comment]
Hey again, and sorry for the late reply.

I don't believe localization of field labels is a core feature. The officially recommended way of doing country specific sites in Umbraco is to have separate content trees, and thus you'd have separate forms (unless you're doing form reuse).

On top of that there's the matter of non-value fields (headings, text paragraphs etc). They don't have a field name that could be used for localization through the dictionary.

However you're in control of the rendering, and you can do pretty much what you want with it. For example, you could fetch the text box label ([this line](https://github.com/kjac/FormEditor/blob/master/Source/Umbraco/Views/Partials/FormEditor/FieldsSync/core.textbox.cshtml#L3)) from the dictionary with a fallback to the defined label by replacing `@Model.Label` with something like this: 

`@Umbraco.Coalesce(Umbraco.GetDictionaryValue("form." + Model.Name.ToLowerInvariant()), Model.Label)`. 

Disclaimer... that code is written in free hand and not tested 😄

**Comment by ragivi** [comment]
Hi kjac!

Your solution is great! The code works perfectly. I know that the officially recommended way is have two separate nodes, but in one site it was a requirement to have only one node (I solved it with Vorto package). 

Thanks a lot.
