### ISSUE TITLE
Paging buttons on same row as submit button

### ISSUE THREAD

**Issue by BarryGibson** [kjac/FormEditor#108]
I would like the paging buttons to be able to be included with the Submit button, at the moment when you have a paged form the next and previous buttons are outside the editable form.
It would also be good to be able customise the labels of the next and previous buttons in the same spot.

**Comment by kjac** [comment]
Hi @BarryGibson,

Paging has been a bit neglected on my part. And you're right, currently the only way of setting the paging button texts is by using the dictionary (which affects all forms).

I am pondering adding a dedicated tab for paging settings. Off the top of my head I'm thinking:
- Labels for paging buttons
- Options for paging button placement (top/bottom/both)

Any thoughts?

**Comment by BarryGibson** [comment]
Hi @kjac within forms I am using paging on I have been including a submit button on each page (Labeled "Save draft" on all but last page. in my case I would prefer to have the control buttons all in one line. 
E.g.:
[Previous Page]  [Save Draft]  [Next Page]

I was considering making a custom submit button field type with an option to include next/previous buttons.

The other thing I was considering was if there should be the ability to have a form header/footer where you could put things that were common per page e.g. instructions and control buttons.

**Comment by kjac** [comment]
@BarryGibson ok... I think your needs require us to go in a different direction (and postpone the paging tab for later). 

I figure if I introduce an option to tell Form Editor *not* to render the paging buttons, you can add your own paging buttons below the form within your own template. It'd be in the same way as you tell Form Editor to fetch the form from another source, via `ViewBag` properties - e.g. setting `ViewBag.FormCustomPagingButtons = true;` in your template before calling the Form Editor rendering partial.

With regards to the form header/footer you should probably implement those as regular Umbraco content - that is, other properties on the doctype that contains the form property.

**Comment by BarryGibson** [comment]
Thanks @kjac that sounds like a good temporary solution.

In relation to the next and previous labels, I think that they should be in the Editor settings as in most cases you would want them consistent across your site.

With regards to the header/footer, I agree that sometimes it should be in Umbraco content. However when using the form editor as a "Reusable form" it is helpful to have all the information for that form encapculated in a single package.

**Comment by kjac** [comment]
@BarryGibson well... you can put the header/footer in your "reusable form" document alongside the form itself too 😄 

If you already have the instance of `IPublishedContent` to put in `ViewBag.FormContent`, you can simply access the header/footer properties from that same instance before/after calling the Form Editor partial view. 

Anyway... I'll add some more hooks for rendering, to allow for those custom paging buttons.
