### ISSUE TITLE
Select box (drop-down) not displaying submitted value

### ISSUE THREAD

**Issue by BarryGibson** [kjac/FormEditor#109]
There is an issue where the Select box (drop-down) is not displaying the submitted value.
(At this stage I have only tested against Async forms however as the code is the same as the default value code I assume it works in all cases)
I have tracked this down and will put in a pull request for review.

**Comment by kjac** [comment]
@BarryGibson's PR will fix this issue in the next release.

**Comment by kjac** [comment]
Deployed with release 0.17.1.1
