### ISSUE TITLE
Form suddenly stops working "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by ralphvanvugt** [kjac/FormEditor#115]
One moment the form shows nicely, but a second later the following error appears:

Object reference not set to an instance of an object.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 
Line 140:
Line 141:      @* form actions as an array of JSON objects *@
Line 142:      _fe[@formContent.Id].actions = @form.Actions.Render();
Line 143:
Line 144:      @* the total number of form pages *@

Source File: c:\inetpub\wwwroot\www.culinaireduizendpoot.nl\Views\Partials\FormEditor\Async.cshtml    Line: 142

We cannot fix it, only by creating a new node and create the form again.

**Comment by kjac** [comment]
Hey. What happens if you comment out line 142 in Async.cshtml?

Den 24. feb. 2017 3.32 PM skrev "Ralph van Vugt" <notifications@github.com>:

**Comment by kjac** [comment]
@ralphvanvugt I'm closing this now. Reopen it if you're still having problems.

**Comment by ralphvanvugt** [comment]
@kjac Sorry, I was on holidays. The fix worked.
