### ISSUE TITLE
Reusable form - get ID of page actually submitted from, for Email template

### ISSUE THREAD

**Issue by cpevans** [kjac/FormEditor#116]
I may be doing something wrong, but here is my scenario.

I have a parent page with many children in Umbraco. Each child page wants to show the same form on it, so the form is defined on the parent page.

The child pages load in the form easily enough by doing this:

ViewBag.FormContent = Model.Content.Parent;

Submissions work fine, everything is ok except for one thing: in the Email that gets sent out, I want to show the name and link of the child page the user actually submitted the form on. But when accessing currentContent in the template (which is taken from ViewData["currentContent"] as IPublishedContent )  I get the parent page where the form is defined, not the page that was actually used to submit the form.

How do I access the correct child page from the Email template? 

Bonus extra credit -- would it be at all possible to record the child page name in the submissions values found inside Umbraco as well?

**Comment by kjac** [comment]
@cpevans I'm happy to hear you've got it all working except that little bit. That's awesome 👍 

You're not doing anything wrong. From a Form Editor perspective, what you're seeing makes sense. All Form Editor really cares about when handling submissions is where to store the submitted data.

That being said, there are several ways to achieve what you're trying to do. But first... are you using asynchronous postback in your form?

**Comment by cpevans** [comment]
Thanks for the moral support!

Yes, I'm using async for this one.

**Comment by kjac** [comment]
@cpevans ok. Async collects the submitted values out of the request context. In this case I'd consider implementing a custom field that keeps track of the originally requested content (the child page) and exposes this as its field value on the server side. You could do this by means of a hidden field in the form.

The downside of this solution is that the field has to be part of the form.

The upside is that the field will be able to show the name of the child page along with the rest of the submitted values in the Umbraco back office.

**Comment by cpevans** [comment]
OK - this sounds good.  I've followed the documentation here:

https://github.com/kjac/FormEditor/blob/master/Docs/extend_field_simple.md

and created a custom hidden field and added it to my form.  

This is my field partial:

```
@inherits Umbraco.Web.Mvc.UmbracoViewPage<FormEditor.Fields.CustomField>

<input type="hidden" id="@Model.FormSafeName" name="@Model.FormSafeName" value="@Umbraco.AssignedContentItem.Name" />
```


I can see in the HTML source of my page that it renders properly, and the value contains the correct page name; 

`<input type="hidden" id="_PageName" name="_PageName" value="Test page with form" />`

but the field value isn't being saved in the form when submitted.  So it's coming through blank in the email, and the submissions list doesn't contain a value for it.

What am I missing? I think I'm pretty close here :)

**Comment by kjac** [comment]
You are pretty close! Good job :-)

It looks like a partial that'd work great for synchronous form submission.
But since you're using async it won't work.

I'll have to update my docs by the looks of it :-P

I'm out of town atm so I can't post a working version for async. I'll do it
tonight. Or if you have itchy fingers, you can try tweaking the partial
yourself using the async partial for the textbox field as a reference.




Den 5. mar. 2017 2.09 AM skrev "Chris Evans" <notifications@github.com>:

**Comment by cpevans** [comment]
is it to do with this on the wrapper div :

action-field="@Model.FormSafeName"

**Comment by kjac** [comment]
I wish I could give you a definitive answer, but my network is so bad here
I can't even get github loading.

The easiest way I can think of to get things up and running is to clone the
textbox partial for async and:

- change the view model from Textbox to CustomField.

- change the input type from text to hidden.

- implement the field value initialization that sets the field value to the
name of the child page.

... Or simply wait until I'm back home tonight so I can post a proper
solution for you :-)



Den 5. mar. 2017 8.25 AM skrev "Chris Evans" <notifications@github.com>:

**Comment by cpevans** [comment]
Hmm ok - done all those steps and still no dice, so hopefully you can take a look later on! Thanks so much for all your help and speedy responses  :)

**Comment by kjac** [comment]
@cpevans Ah... Angular, glorious Angular. I think you'll need to push your field value to `formData` when your field is initialized. Otherwise it won't be added to the form data that's pushed to the server when the form is submitted.

This partial works for me (note the `ng-init`):

```cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<FormEditor.Fields.CustomField>

<input type="hidden" id="@Model.FormSafeName" ng-init="formData.@Model.FormSafeName='@Umbraco.AssignedContentItem.Name'" name="@Model.FormSafeName" />
```

Of course, if you're ever going to use something similar for synchronous form postback, simply setting the field value (as you've been doing so far) should be sufficient.

**Comment by cpevans** [comment]
@kjac success! thanks so much for your prompt and very helpful support. now on to the next great site :)

**Comment by kjac** [comment]
@cpevans always happy to help :)

I'm glad you got it all working.
