### ISSUE TITLE
Destination email address for notification email

### ISSUE THREAD

**Issue by Alistair67** [kjac/FormEditor#117]
Hi,

I'm sure this is more an issue with me that with your software - which is great btw.

I can't seem to work out where to specify a destination email address for the notification email to go to. Could you enlighten me?

Thanks, Alistair

**Comment by kjac** [comment]
Hey @Alistair67,

I'm glad you like it 😄  

The recipient settings are configured on the "Emails" tab on the form itself. 

First make sure that the tab is enabled on the data type configuration, and that you have an email template selected - like this:

![image](https://cloud.githubusercontent.com/assets/7405322/23562692/cfa33314-0043-11e7-8d2c-84f0378eb341.png)

Then you can set up your recipient on the form - like this:

![image](https://cloud.githubusercontent.com/assets/7405322/23562702/ddbd19b0-0043-11e7-8426-305afa1a5891.png)

**Comment by kjac** [comment]
@Alistair67 I'm closing this now - reopen if you're still having problems with this.

**Comment by Alistair67** [comment]
Hi kjac,

Sorry for the tardy response - I'm only in once a week. 

Thanks you very much for your help - I hadn't selected a notification email template which I presume is why the email tab wasn't appearing on the form even though I had it selected in the data type. As I predicted, more of an issue with me than your software! :)

Thanks, Alistair

**Comment by kjac** [comment]
You're welcome :) glad you got it to work.
