### ISSUE TITLE
Lucene index storage 

### ISSUE THREAD

**Issue by bobi33** [kjac/FormEditor#125]
Hi, if form submissions (including uploaded files) are stored in a Lucene index under /App_Data/FormEditor, and if my website has a site-wide search using examine, would any form submissions be searchable by the public using the website?

**Comment by kjac** [comment]
Hey @bobi33,

Don't worry, they won't. Examine only searches the indexes you explicitly specify in the Examine configuration.

**Comment by bobi33** [comment]
Ok, so since I haven't specified formeditor, then it won't...

Thanks @kjac  :)
