### ISSUE TITLE
500 internal server error after attepting to install

### ISSUE THREAD

**Issue by tmrcs** [kjac/FormEditor#129]
Hi,

After trying to install  your package via nuget, my solution has crashed.

When attempting to install  I got he error: "Package 'Microsoft.AspNet.Identity.Core.2.2.1' does not exist in project", and the install rolledback but it left me without access to the website.

Any ideas why this could be?

I did attempt to install on a Umbraco 7.5.X solution, I thought that by 7.3+ you meant it was compatible with all Umbraco versions since 7.3

**Comment by kjac** [comment]
Hi @tmrcs,

Form Editor is indeed compatible with 7.5.x - also when installed via nuget. Did you install Umbraco via nuget too?

The nuget package has a dependency on [UmbracoCms.Core](https://www.nuget.org/packages/UmbracoCms.Core/), which in turn has a dependency that ultimately leads to Microsoft.AspNet.Identity.Core. By the sound of things, you might have unintentionally triggered an installation of UmbracoCms.Core, which then failed for whatever reason. Which leads me to assume you might not have installed Umbraco via nuget?

**Comment by tmrcs** [comment]
Hi @kjac,
We have Umbraco running on our dev server and I do not think it was installed via nuget, rather manually.

I managed to get it working by restoring the package.config, in the stress i did not keep a copy of the one which ahd the problem, so I can not say what the problem was. 

Thanks anyways for your help i @kjac !!

**Comment by tmrcs** [comment]
\

**Comment by kjac** [comment]
Hey @tmrcs,

I'm glad to hear you got it running again.

FYI: Each release on Github contains an Umbraco package you can install within Umbraco, so you don't have to use nuget if you prefer installing via Umbraco.

**Comment by tmrcs** [comment]
Thanks @kjac! will attempt the install with the binaries tomorrow!
