### ISSUE TITLE
Blank back office post installlation of the package via back office

### ISSUE THREAD

**Issue by tmrcs** [kjac/FormEditor#130]
Hi, 

After installing the FormEditor package via the back office, I can no longer access the back office (blank page). I get the following error: 'Error: Argument 'Umbraco.MainController' is not a function, got undefined' in the dev tools.

I tried removing the App_Plugin folder where the manifest is defined but no luck, still get the same error.

Thanks

**Comment by kjac** [comment]
Hey @tmrcs,

That sounds really weird. Which version of Umbraco?

**Comment by tmrcs** [comment]
@kjac 

Umbraco 7.5.11

**Comment by kjac** [comment]
@tmrcs Strange. I just tried installing the Umbraco package from the latest release ("Form.Editor_0.18.1.1.zip") in a brand new Umbraco 7.5.11 site and also a brand new Umbraco 7.5.13 (latest release) site with no problems at all. 

Screenshot from after installing in 7.5.11:

![form editor package install](https://cloud.githubusercontent.com/assets/7405322/24962845/5929375a-1f9d-11e7-912f-72a24f10f30a.png)

Something seems to be up with your Umbraco site 😞 

It might be a caching issue, even though a package installation should explicitly cause a cache bust in the Umbraco back office. But anyway... perhaps it helps if you enable debug in the web.config (`<compilation ... debug="true" ...>`) and refresh the back office with caching disabled in your browser?

**Comment by kjac** [comment]
@tmrcs I'm closing this now.
