### ISSUE TITLE
reCAPTCHA error not showing up

### ISSUE THREAD

**Issue by bobi33** [kjac/FormEditor#132]
Hi,

I've noticed that the reCAPTCHA error message doesn't show up.

**Comment by kjac** [comment]
Hi @bobi33,

I'll have a look at it when I can. Bit swamped at the moment.

However, I'm not sure the error message can actually show up in the async rendering. It's mostly meant for server side validation only, in case people cheat their way around the reCAPTCHA on the client side.

**Comment by kjac** [comment]
Note: See #127 for more info

**Comment by bobi33** [comment]
Sorry for reposting a similar question...I somehow totally lost track of that other issue.

Also, I thought async was better for security purposes, but I didn't realize how finicky it was :s

**Comment by kjac** [comment]
Hey @bobi33,

Async isn't any security improvement :) it's just a UX one, or at least that's what some would argue.

I've fixed the problem but I'm in the process of rewriting the whole reCAPTCHA bit to support the new "invisible reCAPTCHA". I'll release this fix as part of that - I hope you can wait a bit longer.

-Kenn

**Comment by kjac** [comment]
@bobi33 it should be fixed in the latest release :)
