### ISSUE TITLE
Safari: cannot enter any field if safari autocomplete is active

### ISSUE THREAD

**Issue by ralphvanvugt** [kjac/FormEditor#135]
Strange thing happens on Safari 10.1.1 and the lastest version of OS X. If Safari autocomplete is active, none of the fields can be filled in. I don't know if this is a bug or an unfortunate Safari feature.

![image](https://user-images.githubusercontent.com/2463054/26876646-7772de12-4b87-11e7-9cf9-928e1e4ebead.png)

**Comment by kjac** [comment]
@ralphvanvugt I'm pretty sure FormEditor doesn't do anything to prevent focus loss. It's probably a Safari "feature". Are there any console errors?

**Comment by kjac** [comment]
@ralphvanvugt I'm closing this now. If you think it's Form Editor related, feel free to reopen.
