### ISSUE TITLE
Using reCaptcha on multisite installation

### ISSUE THREAD

**Issue by Alistair67** [kjac/FormEditor#136]
Hi,

I have two different sites running on one Umbraco installation and I want to use formEditor on both sites and want to have reCaptcha on both forms. However, if I have to set the Site and Secret keys in web.config appSettings then as far as I can see, it will be wrong for one of the sites.

Is there some way of setting the appSettings dependent on which site you're on?

Cheers, Alistair

**Comment by kjac** [comment]
That's a pretty good point. I'll create a fix for it as soon as I can,
hopefully this weekend.

Thanks for reporting it ☺️

Den 9. jun. 2017 12.12 PM skrev "Alistair67" <notifications@github.com>:

**Comment by Alistair67** [comment]
Wonderful. Thanks for the speedy response.

**Comment by kjac** [comment]
@Alistair67 you know you can use the same key set on multiple domains, right?

![image](https://user-images.githubusercontent.com/7405322/26973774-3e4f15e6-4d18-11e7-9809-2308ffbfd480.png)

**Comment by Alistair67** [comment]
No, I didn't know that. First time using reCaptcha but shoudl have spotted that. Just went ahead and registered the new site without realising I could add it in to an existing key. Sorry to bother you.

Thanks, Alistair

**Comment by kjac** [comment]
Ah well good, problem solved for now then ☺️

Den 9. jun. 2017 5.22 PM skrev "Alistair67" <notifications@github.com>:
