### ISSUE TITLE
Approve submissions

### ISSUE THREAD

**Issue by ralphvanvugt** [kjac/FormEditor#138]
Question / Feature request. I've created a page in which the entries are visible after submitting them using the GetSubmittedValues() method. Works great!

Would it be possible to have the admin approve the post before it becomes visible on the website?

**Comment by kjac** [comment]
Hi @ralphvanvugt,

I've considered implementing an approval system in Form Editor multiple times, but it's not really on the drawing board right now. While there are some obvious use cases for it, you're actually the first to request it, which must mean it's not something people actually need. I'm not saying I won't ever do it - heck I feel tempted to start working on it now - but well... not making any promises :)

If you need something here and now, there is a way to do it, but it's not exactly simple and out-of-the-box kind of stuff. And it also might not suit your needs.

What I'm thinking is this:

1. Create a custom "approval" field type that's only ever rendered for admins, and make sure it's always got the same field name in the form, so you can positively identify it while rendering submissions.

2. Create an place on the website for the admins to edit submissions. You can get some inspiration [here](https://github.com/kjac/FormEditor/blob/master/Tutorials/Receipts.md).

3. When rendering the submissions, filter out all those that do not have an approved state (maybe only for non-admins).

Aside from not being a super simple solution to implement, it might also introduce another problem: If you're rendering the submissions in fixed page sizes, they will start to vary when you filter out unapproved submissions (say you have a page size of 10 and one of them happens to be unapproved, then the actual page size will be 9).

**Comment by kjac** [comment]
@ralphvanvugt ok so I couldn't help myself. I've started the implementation of an approval system. Here's a preview of how it'll work:

![form editor submission approval preview](https://user-images.githubusercontent.com/7405322/28008505-1b1b451a-6558-11e7-9344-0fc6f301619c.gif)

There's no deadline right now, but with some luck I'll find time to get it done before my vacation starts next week.

**Comment by ralphvanvugt** [comment]
@kjac Wow! That looks awesome! Thanks!

Didn't want to put you up with the extra work just before your vacation though ;-)

**Comment by kjac** [comment]
@ralphvanvugt it's ready 😄 

Check the latest release (1.2.0.1).

**Comment by ralphvanvugt** [comment]
Wow! Briljant! Thanks a lot!
