### ISSUE TITLE
Feature request: Regex input validation

### ISSUE THREAD

**Issue by kristoffer-tvera** [kjac/FormEditor#143]
Would this be possible? Thank you.

**Comment by kjac** [comment]
Hi @kristoffer-tvera,

I'm not sure what you're asking here... but if you mean adding regex validation to the built-in form fields, the answer is no. Editors don't understand regex. 

You should consider creating custom field types for your regex needs. It's super simple to create fields, and editors are way better at using them. Check out [the docs](https://github.com/kjac/FormEditor/blob/master/Docs/extend_field_simple.md) for creating simple field types.

**Comment by kristoffer-tvera** [comment]
After reading the documentation, I can see how the feature I want would be implemented.  I was just expecting to see regex as a possibility in the content-ui, like how the default Umbraco-ui when making document types, has a bottom field of validation through regex

**Comment by kjac** [comment]
Cool. I hope you get to build something awesome :) 

I'll close this now, feel free to reopen if it shouldn't have been.
