### ISSUE TITLE
Cant find where to configure email to address

### ISSUE THREAD

**Issue by mikaelekstrom** [kjac/FormEditor#145]
I just installed Form Editior on my Umbraco 7.6.4 version and have configured everything accordingly. But i want there to be a notification sent to an editor when someone fills in the form, but i cant find anywhere to configure that? 

EDIT: 
Just realized that the email tab is missing for some reason, any ideas on how to fix this? 

KR
Mikael

**Comment by kjac** [comment]
Hi @mikaelekstrom,

You'll need to configure email templates for notification and/or confirmation to make the tab appear in the editor.

See the [installation guide](https://github.com/kjac/FormEditor/blob/master/Docs/install.md#email-templates) or [this tutorial](https://github.com/kjac/FormEditor/blob/master/Tutorials/Receipts.md#the-receipt-email) for more info :)

**Comment by mikaelekstrom** [comment]
I have configured it for the notification using the standard template that comes with it. But no menu option appears.

**Comment by kjac** [comment]
It should "just work" once you have selected an email template in the data
type configuration.

You haven't by any chance disabled the emails tab under "Tab order and
availability" within the datatype configuration?

Den 4. sep. 2017 2.56 PM skrev "mikaelekstrom" <notifications@github.com>:

**Comment by mikaelekstrom** [comment]
Cant see that I am missing anything? 

![image](https://user-images.githubusercontent.com/28589973/30048843-5c7aac7a-9218-11e7-8236-3588ddb17aec.png)

**Comment by kjac** [comment]
@mikaelekstrom looks about right. And the "Emails" tab isn't showing in the form editor?

I've just set up a 7.6.5 site with Form Editor 1.2.1, and it works fine on my end:

*Data type config*
![image](https://user-images.githubusercontent.com/7405322/30049634-b2f4774a-921b-11e7-90ae-15431b5f48fe.png)

*Content*
![image](https://user-images.githubusercontent.com/7405322/30049689-d950e09a-921b-11e7-97e7-74b4a1955670.png)

**Comment by mikaelekstrom** [comment]
I am runing the same version of Form Editor but it dosent want to work, cant really figure out what i have done wrong.

**Comment by mikaelekstrom** [comment]
Can you make a quick step by step installation guide and then i can try reinstalling it again. 
Another thing is that i cant find the recaptcha box either when adding things to the form, so maybe i have a broken installation. 

KR
Mikael

**Comment by mikaelekstrom** [comment]
Got it to work, I had missed configuring things when adding the property to a page type. I thought I only had  to configure the data type to get it to work.

Thanks! 
Mike

**Comment by kjac** [comment]
@mikaelekstrom glad you figured it out :) it's created that way so different editors can have notification emails for their respective forms. At the same time it also works as an opt-in for notifications.

I'll go ahead and close this now.
