### ISSUE TITLE
Model.Invalid does not trigger in the fieldtype template

### ISSUE THREAD

**Issue by thomassen88** [kjac/FormEditor#147]
Hi,
Im trying to activate the "has-error" class on the "form-group"-div wrapped around the label and the field, but the class never appear. 
"Model.invalid" wont trigger in the fieldtype template (eksample: core.textbox.cshtml)

I have followed the tutorials to the point, but i cant figure why it wont appear.

One more thing:
Is there a "Valid" definition that i can use to wrap a "success"-class around my field if the field is valid?

**Comment by kjac** [comment]
HI @thomassen88,

The `has-error` class is only set server side, and only if the server side validation fails. Hopefully all validation errors should be caught client side, and you won't ever see it. It's meant as an option to highlight the entire field group (label + field) if there's a server side validation error, to ensure they stand out in case of a full page reload.

As for a `success` class you should look into the AngularJS ("Async") rendering (or roll your own). AngularJS is so kind as to add `ng-valid`/`ng-invalid` classes to the relevant input fields (among other useful classes):

![image](https://user-images.githubusercontent.com/7405322/30691795-3285b78a-9ec9-11e7-841e-2cd557d63571.png)

**Comment by thomassen88** [comment]
@kjac Thank you, that make sense tough.
I will look into AngularJS then.
Thank you for the fast reply and awesome plugin 👍 :)

**Comment by kjac** [comment]
You're welcome, glad you like it!

Den 21. sep. 2017 2.52 PM skrev "Bengt Andre Thomassen" <
notifications@github.com>:
