### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by GuzzyMedia** [kjac/FormEditor#151]
![2017-09-30 23_06_32-](https://user-images.githubusercontent.com/27682662/31049485-7410a558-a634-11e7-99cf-bf118a84776d.png)
![2017-09-30 23_07_29-settings - test](https://user-images.githubusercontent.com/27682662/31049486-74273b74-a634-11e7-9c30-3ab615f8a5eb.png)
![2017-09-30 23_08_06-settings - test](https://user-images.githubusercontent.com/27682662/31049487-74376a12-a634-11e7-8988-48ddbf56dc57.png)

As you can see, i got rendering issues? What did i do wrong? :)

**Comment by kjac** [comment]
Hi @GuzzyMedia,

Looks like you're trying to render a block of Razor within a WebForms template? That won't work :)

Form Editor has no official support for WebForms. If you want to use it in a WebForms context, you'll have to create your own rendering from scratch.

Alternatively you might be able to move the Razor to a macro. Not sure if it'll work, nor how it'll perform (you'll efficiently be mixing two different rendering engines in one page rendering).

-Kenn

**Comment by GuzzyMedia** [comment]
Hello
Thanks for the fast response!
The thing is, that i'm trying to implement your form into a content page, but i'm not sure where to put the razor.. The template, our content page is using is a webform, and I find it as the only place I can put it into... Do you have the time to help me out?

**Comment by GuzzyMedia** [comment]
![2017-10-01 18_39_55-](https://user-images.githubusercontent.com/27682662/31056797-299fde0e-a6d8-11e7-8aa0-e2227a92a6ea.png)
![2017-10-01 18_40_22-developer -](https://user-images.githubusercontent.com/27682662/31056798-29a04826-a6d8-11e7-8625-54ea2319ab94.png)
![2017-10-01 18_40_33-](https://user-images.githubusercontent.com/27682662/31056799-29a09a60-a6d8-11e7-82bf-baf609ed46a7.png)

I've just tried doing it with a macro.. Can't see what i'm doing wrong.. :(

**Comment by kjac** [comment]
The log files should probably give you some clues as to what's wrong with your code. My guess is you need to close the code block before calling `@Html.Partial(...)`.

I just tried creating a WebForms master page that calls a Razor macro with the Form Editor rendering. Looks like it works just fine. 

Keep in mind though that you're still mixing WebForms and Razor in the same rendering, which might have a performance impact. Also there might just be Form Editor specific things that simply won't work with this solution, as it's never been tested like this.

Here's the master page:

```html
<%@ Master Language="C#" MasterPageFile="~/umbraco/masterpages/default.master" AutoEventWireup="true" %>

<asp:Content ContentPlaceHolderID="ContentPlaceHolderDefault" runat="server">

<!DOCTYPE html>
<html>
<head>
  <title>Test WebForms</title>
  <link rel="stylesheet" href="http://getbootstrap.com/dist/css/bootstrap.min.css"/>
  <style>
    /* required field indicator on the field labels */
    div.form-group.required > label:after {
      content: ' *';
      color: #a94442;
    }
  </style>
</head>
<body>

<umbraco:macro alias="FormEditorMacro" runat="server" />

</body>
</html>

</asp:Content>
```

...and here's the macro (I've used the NoScript rendering for simplicity, but it can be whatever):

```cs
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@* render the form with the NoScript partial *@
@Html.Partial("FormEditor/NoScript", Umbraco.AssignedContentItem)
```

**Comment by GuzzyMedia** [comment]
You're amazing! You just saved my day..
It was my macro that had some difficulties..
As you can see, i'm still pretty new to Umbraco, so i learned alot from this! 👍  
Thanks alot!

**Comment by kjac** [comment]
You're welcome. Glad you got it working.
