### ISSUE TITLE
Error with angular

### ISSUE THREAD

**Issue by raulribeiro** [kjac/FormEditor#152]
hello,

i've started having this error, can you help me?

https://user-images.githubusercontent.com/6097393/31117002-1509586e-a820-11e7-9921-77e1796bb3e5.png

**Comment by kjac** [comment]
Hi @raulribeiro ... looks like something's wrong with your Umbraco install. Those URLs are in fact templates from the Form Editor core.

Did you do an upgrade or something similar to cause this?

**Comment by raulribeiro** [comment]
i've updated some assemblies, but i didn't changed the umbraco installation
i have some forms created, can i unistall formeditor and install again without losing the created forms?

**Comment by raulribeiro** [comment]
i've uninstalled the package and installed again. it's working :)

**Comment by kjac** [comment]
Hey again. That's good news :)

I suspect you've experienced some glitch in Client Dependency here. Might have been enough just to clear your clientside cache to solve it.

I'm closing the issue, glad you got it all working again.
