### ISSUE TITLE
Actions not working

### ISSUE THREAD

**Issue by raulribeiro** [kjac/FormEditor#153]
For some reason validations are working but actions doesn't do anyhing.

Can someone help me?

**Comment by raulribeiro** [comment]
![image](https://user-images.githubusercontent.com/6097393/31413237-3a7dd35e-ae10-11e7-822c-5a3b573a3684.png)

**Comment by kjac** [comment]
Hi @raulribeiro,

By the looks of things you're using the Sync rendering. It works fine on my end with my test actions, but maybe you've somehow created an action that causes the JS to fail?

You need to add some specifics about the error and how it can be reproduced.

Here's a GIF showing how the Sync rendering works in my test:

![issue153](https://user-images.githubusercontent.com/7405322/31426892-7dde7b94-ae65-11e7-903e-a415ad264a46.gif)

**Comment by kjac** [comment]
Closing this now.
