### ISSUE TITLE
Should be comma separated not semi-colon separated.

### ISSUE THREAD

**Issue by dbardi** [kjac/FormEditor#154]
https://github.com/kjac/FormEditor/blob/600c91b22bab6d9b04b5ec8d8d45bacb8760cb99/Source/Solution/FormEditor/Api/CsvExport.cs#L115

**Comment by dbardi** [comment]
Maybe an option in the FormEditor.config or the datatype to set the delimiter.

**Comment by uniquelau** [comment]
Excel struggles with reading the export, examples below:

![excel screenshot](https://user-images.githubusercontent.com/914735/32553611-4c108f86-c48f-11e7-9348-687025d879e2.JPG)

[Form data 2017-11-08 12-34.xlsx](https://github.com/kjac/FormEditor/files/1454185/Form.data.2017-11-08.12-34.xlsx)

**Comment by kjac** [comment]
@uniquelau @dbardi I meant to address this issue earlier today but got distracted. 

As of version 1.3 the delimiter is configurable in the Form Editor config file; check [the docs](https://github.com/kjac/FormEditor/blob/master/Docs/install.md#csv-export-format) for more insight.

@dbardi please note that the config syntax is a little bit different from your original PR.

**Comment by uniquelau** [comment]
Set to comma, and Excel is happy 👍

**Comment by kjac** [comment]
I'm beginning to suspect that my Excel is the only one in the whole wide
world that likes semicolons better... :P

Den 8. nov. 2017 4.12 PM skrev "Laurence Gillian" <notifications@github.com

**Comment by kjac** [comment]
Closing this now :)

**Comment by uniquelau** [comment]
For future reference, I think this issue is a regional/windows issue, as I noticed UI-O-Matic is working in the same way, using a semi colon.

https://github.com/TimGeyssens/UIOMatic-Addons-Export
https://github.com/TimGeyssens/UIOMatic-Addons-Export/issues/3

More details here:
https://stackoverflow.com/questions/10140999/csv-with-comma-or-semicolon
