### ISSUE TITLE
Error when submitting form

### ISSUE THREAD

**Issue by dbardi** [kjac/FormEditor#156]
"The requested resource does not support http method 'GET'."

FormEditorWidget is an IPublishedContent with a property called Form.
Form renders correctly, but can't submit without error.
The method appears to require HttpGet attribute.

`@using ClientDependency.Core.Mvc
@model Models.FormEditorWidget
@{
    Html.RequiresJs("//ajax.googleapis.com/ajax/libs/angularjs/1.6.5/angular.min.js", 0);
    Html.RequiresJs("/JS/FormEditor/FormEditorAsync.js");
}
@Html.Partial("FormEditor/ASync", Model)`

https://github.com/kjac/FormEditor/blob/600c91b22bab6d9b04b5ec8d8d45bacb8760cb99/Source/Solution/FormEditor/Api/PublicController.cs#L23

**Comment by kjac** [comment]
Hey @dbardi ... not sure why the *** GitHub has stopped sending me mail notifications. Anyway, I just saw your issues now.

Anyway... submission must use POST - you can't submit using GET. The bundled JS should perform a POST out of the box: https://github.com/kjac/FormEditor/blob/master/Source/Umbraco/JS/FormEditor/FormEditorAsync.js#L161

**Comment by dbardi** [comment]
Thanks.. was an issue on my end.
