### ISSUE TITLE
[Feature Request] Add file upload field value as attachment to notification &| confirmation email templates

### ISSUE THREAD

**Issue by jonrandahl** [kjac/FormEditor#16]
@kjac 
Hope you're well!
I've been asked if there any way to add an attachment to the sent emails if a file is uploaded?

I've gone through the code and wondered what you thought would be the best way to update the ```private static void SendEmails``` method on line 404 of _FormEditor/Source/Solution/FormEditor/FormModel.cs_ to be able to pass in the file upload value/path as an attachment as such:

```
 MailMessage message = new MailMessage {
                From = from,
                Subject = subject,
                Body = body,
                IsBodyHtml = (body.Contains("<html") || body.Contains("<body")) || body.Contains("<div")
            };


Attachment at = new Attachment(Server.MapPath("~/UPLOADED/PATH/GOES/HERE"));
message.Attachments.Add(at);
```

Maybe with an overload of the method based on a checkbox in the back office file upload field asking "Attach to email(s)"? 

Thoughts?
J

**Comment by kjac** [comment]
Hey @jonrandahl 

My first thought was "what a great idea" :)

I've been mulling it over for a few hours now, and I'm leaning towards another option: A link download the file from the site. It'd require a little more work, but would prevent the usual problems with associated attached files (file size or file type issues).

Provided you'd have something like ```UploadField.DownloadFileUrl()``` available, would that be a feasible way to go?

**Comment by jonrandahl** [comment]
Glad to see I'm giving you food for thought @kjac; loving the new response message ui too! :-D

With the request, two things spring to mind immediately:
1. You've brilliantly already given us both the option to set a maximum files size and allowed types on a file upload field 
2. There is a failover maximum file size limit set in the back office through the web.config
so while I can see your point on the associated size and types you've mentioned I feel the safety measures are already in place and this would be a massive benefit to all in the long run?

Have I persuaded you? ;-)
J

**Comment by kjac** [comment]
@jonrandahl You have. I'm concerned about performance, but sending the notification mail as fire-and-forget might do the trick. 

I'll have a look at it soon.

**Comment by kjac** [comment]
@jonrandahl Have a look at #18 :)

**Comment by kjac** [comment]
Done and ready in Version 0.11.1.1 - enjoy.
