### ISSUE TITLE
Submissions - Scroll bar disappears

### ISSUE THREAD

**Issue by uniquelau** [kjac/FormEditor#161]
When a viewing form submissions that have multiple fields, the table overflows and a scroll bar appears.

However, in Chrome, this scroll bar seems to disappear and is not possible to click.

I can scroll the submissions, if I highlight some text and drag it. 

The scroll appears momentarily, and then disappears again. 

CSS is my cup of tea, so I had a good look at what's going on inside `form.css`, but I could not make an adjustment that resolves the issue. Is it something you've seen? I'm happy to have a bit more of a dig, if it helps. I think it may be something to do with something else in the DOM.

**Comment by kjac** [comment]
Hey @uniquelau,

I can't seem to reproduce this - here's how I see it in Chrome:

![image](https://user-images.githubusercontent.com/7405322/32698987-af1dfc7c-c7ae-11e7-8251-9f86ae04a18c.png)

Which Umbraco and Form Editor versions are you using?

**Comment by uniquelau** [comment]
Latest version of Form Editor (1.3.0) and Umbraco 7.7.2, I'll have another play tomorrow! Cheers! L

**Comment by kjac** [comment]
Hey again :)

This is how I see it unfold in Umbraco 7.7.3 with the latest Form Editor:

![image](https://user-images.githubusercontent.com/7405322/32767297-0b11e5ba-c913-11e7-8421-bc0dc83a55ae.png)

**Comment by uniquelau** [comment]
Upgraded to latest Umbraco version, issue is resolved.
