### ISSUE TITLE
Form indexes end up in parent application when CMS is deployed to a sub directory

### ISSUE THREAD

**Issue by joel-cass** [kjac/FormEditor#164]
The Indexes will end up in the incorrect folder when the CMS is deployed to a virtual directory within a parent application. If permissions are not set up, a 500 error occurs on the editor screen.

https://github.com/kjac/FormEditor/blob/036d93adcbc665fccea8147ed449b88d9e4a0b3b/Source/Solution/FormEditor/Storage/Index.cs#L477

I'm pretty sure this can be solved by changing the line to ```return new DirectoryInfo(HostingEnvironment.MapPath($"~/App_Data/FormEditor/{_contentId}"));```

**Comment by kjac** [comment]
Hey,

I'm sure you're right. I'll have a look at it this weekend. 

Thanks for reporting.

**Comment by kjac** [comment]
@joel-cass 1.3.1.0 is out now with a fix for this issue :)
