### ISSUE TITLE
Configuration is not picked up when website is run in a sub folder

### ISSUE THREAD

**Issue by joel-cass** [kjac/FormEditor#167]
Hello,

I found an issue related to running the website in a subfolder, where configuration in config/FormEditor.config is not picked up. I think I have traced it to line 27 in configuration.cs:

https://github.com/kjac/FormEditor/blob/036d93adcbc665fccea8147ed449b88d9e4a0b3b/Source/Solution/FormEditor/Configuration.cs#L27

I think the solution is to add a tilde to the path so that `HostingEnvironment.MapPath(@"/config/formEditor.config")` becomes `HostingEnvironment.MapPath(@"~/config/formEditor.config")`

Thanks

**Comment by kjac** [comment]
@joel-cass I think you're right :)

I'll be putting out a patch release one of the coming days, this will be in it.

Thanks for reporting 👍

**Comment by kjac** [comment]
@joel-cass this is fixed in v1.3.1.1
