### ISSUE TITLE
Checkbox Group invalid when option checked

### ISSUE THREAD

**Issue by uniquelau** [kjac/FormEditor#168]
I have a checkbox group on my form, since upgrading to V1.3.1, if one of the boxes is checked the form fails validation.

I've created new fields and unchecked required, but the error still persists.

The response is:

`{"invalidFields":[{"name":"Availability 2","formSafeName":"_Availability_2","submittedValue":"[\"Monday\",\"Tuesday\",\"Wednesday\",\"Thursday\",\"Friday\"]","invalid":true}],"failedValidations":[]}`

When no boxes are checked, the form can be posted.

Any suggestions on how to start debugging this one?

**Comment by kjac** [comment]
Hey @uniquelau,

Looks like you've stumbled across a bug here. Surprised noone's found it before, from what I can see it's been around for ages :)

I'll create a patch for it in a day or two.

Thanks for reporting 👍

**Comment by kjac** [comment]
@uniquelau this is fixed in v1.3.1.1
