### ISSUE TITLE
Set fields values programmatically during form initialization

### ISSUE THREAD

**Issue by alecrt** [kjac/FormEditor#17]
Hi kjac,

here again with another question :P
 
I'm building a simple hotel website with a booking-form inside a dedicated page.
In the header of all other website pages there's a fast mini-booking-form with only 3 fields: dateFrom, dateTo, number of persons.

When the fast-form has been submitted a GET request is created against the bookingPage Url. 
What I'd like to achieve is set each form field value to the corresponding query string value.

The little problem I have is that SubmittedValue property has protected setter.

Any idea on how could I achieve that?
Thank you,
Alessandro

**Comment by kjac** [comment]
Hey @alecrt,

Maybe you should consider extracting those values in your form template and passing them along to the field partials in a custom model? In this way the field partials could init their field values from either the SubmittedValue or the extracted values.

**Comment by alecrt** [comment]
Yep, could be a valid solution. Thx!

**Comment by kjac** [comment]
Closing this now :)
