### ISSUE TITLE
GetFormModelProperty function not considering compositions

### ISSUE THREAD

**Issue by joshreid** [kjac/FormEditor#172]
Hi @kjac 

I have found that the GetFormModelProperty function does not consider the possibility of property being in a composition in the contentType.

So I have revised code in ContentHelper.cs below to fix - can give pull request if you want.

```
public static PropertyType GetFormModelProperty(IContentType contentType)
{
	List<PropertyType> propertyTypes = contentType.PropertyTypes.ToList();
	propertyTypes.AddRange(contentType.CompositionPropertyTypes);
			
	var property = propertyTypes.FirstOrDefault(p => p.PropertyEditorAlias == FormModel.PropertyEditorAlias);
	return property;
}
```

Let me know if you need anything else and when you'll repackage - I'll run my custom built dll for now.

**Comment by kjac** [comment]
Hi @joshreid,

Awesome, thank you!

Just to avoid creating the list if we don't have to, could you try this code and see if that works for you as well?

```cs
public static PropertyType GetFormModelProperty(IContentType contentType)
{
  bool IsFormModelPropertyEditor(PropertyType p) => p.PropertyEditorAlias == FormModel.PropertyEditorAlias;

  return contentType.PropertyTypes.FirstOrDefault(IsFormModelPropertyEditor)
         ?? contentType.CompositionPropertyTypes.FirstOrDefault(IsFormModelPropertyEditor);
}
```

**Comment by joshreid** [comment]
All good thanks @kjac - yep that's better, and works as expected.

**Comment by kjac** [comment]
Whoops, this one's in the latest version :) closing it now.
