### ISSUE TITLE
Has User Submitted Logic Fails for Logged in Members

### ISSUE THREAD

**Issue by Attackmonkey** [kjac/FormEditor#176]
The logic for checking whether a user can make a submission is flawed on sites with Umbraco members, when used on shared machines.

To replicate, create a poll on your website, and create two members. Add the poll to one of your members only pages.

Fill out the poll with the first member. Log out. Log in with the second member. The second member will not be able to complete the poll, as the plugin thinks they've already completed the poll because the cookie is set.

There should probably be some extra logic in there to account for logged in members so that if there are multiple members using the same browser (in the example of say a shared family computer or a public library computer), they are all able to submit the poll.

**Comment by kjac** [comment]
Hi @Attackmonkey,

I see your point. On the other hand, creating member specific limitations opens up for the opposite issue; a member would always be able to submit a form twice, if it as publicly available (as anonymous and as logged in). Do you see a solution that handles both problems?

Also, in case you're not aware you can roll your own solution by replacing the default "max submissions handler" - see [the docs](https://github.com/kjac/FormEditor/blob/master/Docs/extend.md#custom-handling-of-submission-limitations) and [this issue](https://github.com/kjac/FormEditor/issues/80).

As a bit of background info I should add that the current solution was inspired by [Survey Moneky](https://help.surveymonkey.com/articles/en_US/kb/What-settings-allow-multiple-responses-from-one-computer) (see the "One Response" section).

**Comment by kjac** [comment]
Cool 👍 

Sounds like the simplest way around your requirement would be to clone the [default handler}(https://github.com/kjac/FormEditor/blob/master/Source/Solution/FormEditor/Limitations/MaxSubmissionsForCurrentUserHandler.cs) and change the cookie name to something that includes the current member ID.
