### ISSUE TITLE
UX - Submit Button (when form is missing button)

### ISSUE THREAD

**Issue by uniquelau** [kjac/FormEditor#178]
It is possible to save a form, that does not have a submit button.

It might be nice, if when saving a form without a submit button, a message appeared.

"Your form does not have a submit button, you'll need one for submissions!

**Comment by kjac** [comment]
@uniquelau while I completely agree with this, I'm not sure how to pull it off. There are two different submit button fields in the core alone ([`SubmitButtonField`](https://github.com/kjac/FormEditor/blob/master/Source/Solution/FormEditor/Fields/SubmitButtonField.cs) and [`InvisibleReCaptchaField`](https://github.com/kjac/FormEditor/blob/master/Source/Solution/FormEditor/Fields/InvisibleReCaptchaField.cs)), not to mention whatever custom submit button fields might have been added in various implementations. How does one go about testing if one of these fields exist in the form? Any input would be helpful 😄

**Comment by uniquelau** [comment]
Thank's for the comment, I'll have a bit of a think! And come back in the next few weeks.

**Comment by kjac** [comment]
@uniquelau I'm closing this ... feel free to reopen if you have any great ideas 😄
