### ISSUE TITLE
No form Editor form was found on the page

### ISSUE THREAD

**Issue by rocifier** [kjac/FormEditor#181]
Hi, when I followed the quick-start instructions to add a form to a new template, I don't see any form rendered. Instead, I see a comment tag added to my html: `<!-- no Form Editor form was found on the page -->`. Below are my minimum steps to reproduce:

Add a home page template to a blank Umbraco Cloud setup which includes the recommended form partial:

```
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.HomePage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

<html>
    <body>
        Contact Us
        
        @Html.Partial("FormEditor/NoScript", Umbraco.AssignedContentItem)
    </body>
</html>
```

Create a node using a new document type that consists of a Form Editor on a tab linked to the above template. The form editor is configured on the content item to look like a basic "contact us" form.

View the website, and see the comment being added instead of the "contact us" form, as expected.

**Comment by rocifier** [comment]
I missed an important sentence in the quickstart guide: naming the form alias "form". After renaming the alias, the form renders successfully and works. You may close this issue :)

**Comment by kjac** [comment]
@rocifier I was about to suggest that too :) glad you figured it out.
