### ISSUE TITLE
Form Editor Submissions not showing up for Info Page template

### ISSUE THREAD

**Issue by MattDion** [kjac/FormEditor#182]
Hello,

I try to load the form into a template with a bit more stuff (From Form Editor to Info Page).  

The only problem is that we cant see the submissions anymore using that document type/Template.

Any clue why by any chance?

It also give that warning in Umbraco log trace:

FormEditor.FormModel : Could not submit form data to the web service - the web service endpoint URL was not configured correctly 

Print screen showing there are no submission:
![sdf](https://user-images.githubusercontent.com/8435226/37851990-89e7403a-2ea6-11e8-9129-afc8eeb606a9.png)

Print screen showing them when switching back to original template:
![sad](https://user-images.githubusercontent.com/8435226/37852398-074eba84-2ea8-11e8-883e-17c3c518a17d.png)

Thanks,

**Comment by kjac** [comment]
Hi @MattDion,

Disregard the warning; that's been fixed in the latest version. 

Have you had a look at [the rendering docs](https://github.com/kjac/FormEditor/blob/master/Docs/render.md)? You should be able to apply the steps outlined in the docs to your "Info Page" template.

**Comment by MattDion** [comment]
It Works like a charm thank you!!

This is actually working way better than umbraco form for our needs...!!

Great job!!

Mathieu

**Comment by MattDion** [comment]
Hello,

I just reopened the issue as I though it would work. But no it does not work. I checked every steps...

There must be something in configuration??

everything render good. The form shows up. The form submit. THe only problem is to visualize the submitted form in the submission tab. They dont show up. As soon we switch back to the original template then they show up. Switching document type... Any clue?

![image](https://user-images.githubusercontent.com/8435226/37929172-73354e60-30fc-11e8-9ae8-c7b6e00b2ed6.png)

**Comment by kjac** [comment]
Hi again!

By the looks of it, your form property resides on a document type composition. Do you have the [latest version](https://github.com/kjac/FormEditor/releases/latest) of Form Editor installed? There was an issue in the earlier versions with compositions, which *should* have been fixed in version 1.3.2.0.

**Comment by MattDion** [comment]
Hello,

the issue was the template used was inheriting settings overlapping...

I created a brand new template and added piece by piece... I found the problem.

Your package works like a charm. We actually prefer it better than Umbraco forms...

Great work!

**Comment by kjac** [comment]
@MattDion that's awesome! Good thing you figured it out. I'm glad you like the package :)

**Comment by kjac** [comment]
@MattDion I'm happy to hear that. No money needed though. I didn't create the package for profit. 

Form Editor is only promoted by word of mouth (and a little bit on Twitter), so... tell your friends 😁
