### ISSUE TITLE
Custom conditions still triggering a server side error

### ISSUE THREAD

**Issue by MattDion** [kjac/FormEditor#183]
Followed the documentation:
https://github.com/kjac/FormEditor/blob/master/Docs/extend_condition.md
https://github.com/kjac/FormEditor/blob/master/Docs/extend_condition_advanced.md
https://github.com/kjac/FormEditor/blob/master/Docs/extend_condition_simple.md

But I can’t figure out how to not trigger some sort of server side validation

The client side validation is working as expected, however server side validation still gets triggered.  Example of the results being returned:
{"invalidFields":[],"failedValidations":[{"rules":[{"field":{"name":"Text box","formSafeName":"_Text_box","submittedValue":"qweqweqweqwe","invalid":false},"condition":{"type":"my.length"}}],"errorMessage":"length!!!","invalid":true}]}

**Comment by kjac** [comment]
Hey @MattDion,

I'm able to reproduce your issue. Looks like it happens with conditions by configurations only, and only when the conditions are all by configurations for a given field. 

I'll have a look at a fix as soon as I can :)

Thanks for reporting! 👍

**Comment by kjac** [comment]
@MattDion the new release (1.3.2.1) fixes this issue. Thanks again :)

**Comment by MattDion** [comment]
Thank you for the new release!!! It works perfect!! We might have add a very nice feature. and will fork soon ;)
