### ISSUE TITLE
When a "checkbox group" is marked as required, the form can be be submitted unchecked

### ISSUE THREAD

**Issue by uniquelau** [kjac/FormEditor#184]
![image](https://user-images.githubusercontent.com/914735/38567708-c8b1274a-3cde-11e8-8b09-c6cfdaa2f5ab.png)

**Comment by kjac** [comment]
Hi @uniquelau,

Thanks! I can reproduce this in the async rendering but not in the sync rendering - I hope you're using the async?

If you want a quick fix, make one of the checkbox values selected by default; it'll trigger the validation routines.

I'll make sure to release a proper fix soon.

**Comment by kjac** [comment]
@uniquelau the latest release (1.3.2.1) fixes this issue properly. Thanks again for reporting.
