### ISSUE TITLE
Is FormEditor Angular 5+ compatible?

### ISSUE THREAD

**Issue by biapar** [kjac/FormEditor#185]
Is FormEditor Angular 5+ compatible?
If yes, Is there some example?
Thanks.

**Comment by kjac** [comment]
Hi. There're are no samples of angular 2+ support. But it should be possible to tweak the angular 1 solution. Alternatively have a look at the noscript rendering and go from there.

**Comment by kjac** [comment]
Closing this now due to lack of activity.
