### ISSUE TITLE
Not seeing reCaptcha field

### ISSUE THREAD

**Issue by chrno1209** [kjac/FormEditor#187]
Hi,
I install FormEditor on my Umbraco project but couldn't see reCaptcha field to select, what else did I miss?
Thanks.

**Comment by MattDion** [comment]
It works very good for us... I just tested with the new version and it works...

**Comment by chrno1209** [comment]
Just tested again and it works, I missed the configuration for reCaptcha, thanks so much for your support :).
Close ticket now.
