### ISSUE TITLE
Image url from submission

### ISSUE THREAD

**Issue by alex-grading** [kjac/FormEditor#188]
Hello i want to display images that users upload. How can i get the url path?
I'm only able to get the name:

var uploadField = row.Fields.FirstOrDefault(f => f.FormSafeName.ToLowerInvariant().Contains("image"));
<img src="@uploadField.Value" alt="">

**Comment by kjac** [comment]
Hi @alex-grading,

To put it shot: You can't do that with the built-in upload field.

The built-in upload field lets the storage index handle the file storage. And none of the built-in storage indexes lets you access the uploaded files through a regular GET request. It's a matter of security - uploaded files might contain sensitive information.

If you need to do something along these lines, I suggest you implement your own upload field to handle this specific purpose. You can use the [existing implementation](https://github.com/kjac/FormEditor/blob/master/Source/Solution/FormEditor/Fields/UploadField.cs) as a starting point and go from there. But I can't stress enough that you shouldn't ever use this custom field for regular file uploads - again for security reasons.

**Comment by kjac** [comment]
Closing this now due to lack of activity.
