### ISSUE TITLE
Hyperlinks in form

### ISSUE THREAD

**Issue by bobi33** [kjac/FormEditor#190]
Hi, this is a question about adding in links to checkboxes ... For example: a checkbox that indicates: "I have read the terms and conditions and privacy policy." In this example, the words "terms and conditions" and "privacy policy" will have hyperlinks attached to allow users to read those policies.

**Comment by kjac** [comment]
Hi @bobi33,

Have you checked the *Submission consent* field that was introduced as part of the [GDPR compliance](https://github.com/kjac/FormEditor/blob/master/Docs/GDPR.md#form-editor-and-the-gdpr)?

**Comment by bobi33** [comment]
I think this can be closed. Thanks.

**Comment by kjac** [comment]
Cool :)
