### ISSUE TITLE
How to redirect the user to external page like Paypal after submit?

### ISSUE THREAD

**Issue by biapar** [kjac/FormEditor#194]
How to redirect the user to external page like Paypal after submit?

**Comment by kjac** [comment]
Hi @biapar,

That is not supported out of the box, but you can work around it in a number of ways:

1. Inject your logic into the Form Editor rendering - e.g. after [this line](https://github.com/kjac/FormEditor/blob/master/Source/Umbraco/Views/Partials/FormEditor/NoScript.cshtml#L36) if you're using the NoScript rendering. This may be a bit more tricky to do with the Async rendering, as you'd need to inject your logic into the bundled JS somewhere around [this line](https://github.com/kjac/FormEditor/blob/master/Source/Umbraco/JS/FormEditor/FormEditorAsync.js#L175).

2. Let the receipt page template/controller perform the appropriate redirect. Possibly by using session variables or the like, if you need to pass a state to your external page.

3. Use the built-in [form submission events](https://github.com/kjac/FormEditor/blob/master/Docs/extend.md#form-submission-events) - particularly the `AfterAddToIndex`. You might be able to perform a good oldfashioned Response.Redirect() in your event handler. I'm not 100% sure it'll actually work (it definitively won't if you're using any kind of asynchronous submission), but might be worth a shot. Note that if it does work, you'll be terminating the response before any confirmation emails are sent - thus they're never sent.

I hope that helps some.

**Comment by biapar** [comment]
The better is the point 2 because the 1 I've to change the JS core code and maybe overwritten by an update.
For the point 2, I've to redirect the user to an Umbraco Page and then redirect it to Paypal.
Why Do you not add the feature to redirect to external page like to already redirect to internal Umbraco page?

**Comment by kjac** [comment]
Hi @biapar,

I'm limited to use the pickers that are built into Umbraco, and the content picker doesn't allow for defining external URLs. That's why :)

I'm closing this now. Feel free to reopen if you need any further info.
