### ISSUE TITLE
Partial Submission

### ISSUE THREAD

**Issue by jjbrunton** [kjac/FormEditor#195]
Has anyone attempted to wrap up partial submission with this plugin?

I'm looking for a way for users to save their progress and resume. First thoughts were to make an ajax wrapper above the form itself which would be constantly saving to either Umbraco DB or some external DB. I'd then have a content page that would retrieve the active records for the current user, it'd then load the form and the ajax would then retrieve the active data and populate the form.

**Comment by kjac** [comment]
Hi @jjbrunton,

To my knowledge that's not been attempted :)

It sounds like you need to create your own rendering... reusing the existing ones might prove a bit of a challenge, both in terms of injecting existing values and saving the progress on the fly.

If I was you I'd probably look into the NoScript rendering and see if it's possible to watch the changes to the form fields; then create some save handling - either on the server or in the browser local storage. 

If you end up saving progress to the server, you should be able to seed the `FormModel` with the saved values before subsequent form renderings.

**Comment by jjbrunton** [comment]
Thanks for the input @kjac! I just wanted to check if this had been done before attempting to do it :)

**Comment by kjac** [comment]
Cool! Let me know if you manage to work something out :)
