### ISSUE TITLE
Storing data with SqlIndex

### ISSUE THREAD

**Issue by dirgayudha** [kjac/FormEditor#199]
I`m trying to work with SqlIndex,
followed the samples :
- Save the index, entry and files in Storage and set copy always to store it in bin), 
- Add ApplicationEvents to create the tables for the index
- Uncomment the SqlIndex in FormEditor.Config to enable it.

my umbraco current db is updated with 2 tables created (Entry and files table), but when i tried to to form submission, its still going to Lucene index folder.
I check to break in Add action in Index file, but its not firing to Add action.

Is there anything i need to know to save the data to Umbraco current db ?

**Comment by kjac** [comment]
Hey @dirgayudha. Sounds like the Form Editor core can't find the SQL index implementation, so it reverts to the default (Lucene based) implementation. 

Maybe there's a hint in the Umbraco logs - look for entries beginning with "Could not load custom".

**Comment by dirgayudha** [comment]
so i receive this in the log : 
2018-11-28 15:05:20,089 [P14816/D2/T11] ERROR FormEditor.FormModel - Could not load custom ndex type (requested content ID: 1061)
System.Configuration.ConfigurationErrorsException: Custom ndex type "FormEditor.SqlIndex.Storage.Index, FormEditor.SqlIndex" could not be found
   at FormEditor.Configuration.ParseType(XElement element, Type declaration, Func`2 validateType)

even though i already follow the same example.

**Comment by dirgayudha** [comment]
@kjac ah i found what's wrong... the FormEditor.SqlIndex in the type is the name of the project. 
Because my project name is different, it cannot be found.

Thanks for the hint!
