### ISSUE TITLE
Opening older issue again

### ISSUE THREAD

**Issue by bob-2165** [kjac/FormEditor#203]
I let this lapse. Would a video be helpful for the purpose of troubleshooting this issue?

I get this issue when I go to:
1. Content > node with contact form.
2. "Emails" to change the recipient address to the desired one. I also keep the sender email address as the same one in the Umbraco .config file.
3. I then go to Settings > Document Types > contact form node > I click on the gear in form editor > then the gear again > I scroll all the way down to the SMTP settings > I input a username (Username 1) and password.
4. If I then go to Settings > Document Types > second contact form node > and repeat the above steps to configure the SMTP settings to input a second username (Username 2) and password, this overwrites the previous Username 1 in the first contact form node, so if I go back to the initial contact form node SMTP settings, I will then see Username 2 instead of Username 1.

Am I doing something wrong here?

_Originally posted by @bobi33 in https://github.com/kjac/FormEditor/issues/196#issuecomment-443950711_

**Comment by kjac** [comment]
Hi @bobi33. I'm sorry but utterly confused. There's no SMTP settings configurable anywhere in Form Editor... at least none that I know of?

I'm pretty sure a video might clarify the issue.

**Comment by bob-2165** [comment]
@kjac sorry for the confusion. Here's the video. As you can see the form editor web service username and password of one doc type is linked to another. I have a feeling I'm doing something wrong. Ideally I want the contact us page to have one type of web service username and password and the careers-send-resume doc type to have another web service username and password. I hope this is clearer.

Sorry for the bad resolution...it won't let me upload anything better.

[Video for KJac re formeditor-480.mov.zip](https://github.com/kjac/FormEditor/files/2974251/Video.for.KJac.re.formeditor-480.mov.zip)

**Comment by kjac** [comment]
Hi again. 

You have reused the same instance a Form Editor datatype on both document types. That's why you see the configuration changing on both document types when you edit the datatype on either of them.

If you look closely this is exactly what the big red warning in the top of the "edit datatype" dialog is trying to tell you 😄 

If you want individually configured datatypes on each document type, you need to create specific datatypes for each document type.

**Comment by bob-2165** [comment]
@kjac  Thanks! Such a silly mistake. I couldn't figure out what I was doing wrong 😩

**Comment by bob-2165** [comment]
@kjac so now I have created a new data type called Form Editor (2) while maintaining the same property settings as the original data type in a new document type (doc type 2) which will handle the second form submissions. I have added the second inbox mailtrap username and password credentials to the new Form Editor (2) web service integration. I have also changed the recipient email address associated with the new second form content node from mail1@email.com to mail2@email.com, which follows the autoforward email address in the new mailbox in mail trap. However, something strange is happening. I am noticing that even with the new Form Editor (2) configuration for the second form, the submissions are still going to the original mailtrap inbox, which makes no sense given the new property type. 

**After some testing this looks like it is due to there only being one option in the web.config smtp mailsettings to add one set of web service credentials. I tested this by changing the smtp mail settings credentials to the second mailbox. So essentially this overrides any web service settings in form editor.

I currently have an smtp mail settings set up in the web.config with the same mail trap username and password credentials as the first Form Editor data type (original form) with port 465. This might be overriding 

Any ideas? I thought creating the new data type would allow me to have form submissions for form 2 be sent to a new mailbox in mail trap altogether.**

**Comment by kjac** [comment]
@bobi33 I'm not sure why you'd think the web service integration would be used for sending out mails. If you refer to [the docs](https://github.com/kjac/FormEditor/blob/master/Docs/install.md#email-templates), you'll see that emails are sent using the mail server specified in the `<mailSettings/>` configuration in web.config.

However... you can specify a specific recipient email per form for notification emails - see the "Emails" tab. This should solve your requirement since you obviously have different forms (from different doctypes).

**Comment by bob-2165** [comment]
@kjac I am likely confused, but I thought that the web service integration sends the form content to a web service like mailtrap, which I have yet to see; but I guess without an actual web service set up in c# integrating mailtrap any post actions to my mailtrap username and password and https://mailtrap.io as the web service url did absolutely nothing when listing that in the web service integration of the data type...so in short no form info was sent to mailtrap. Is my understanding correct?
