### ISSUE TITLE
How to integrate with an app

### ISSUE THREAD

**Issue by bob-2165** [kjac/FormEditor#204]
Hi @kjac, hope all is well. Do you know of any ways to integrate form editor with an app. So if an app is built which obtains form information, and then that information is parsed to form editor to store in the backend? I.e. fill out a form on an app and then that information appears in Umbraco.

**Comment by kjac** [comment]
Hi @bobi33. You can have a look in the [docs](https://github.com/kjac/FormEditor/blob/master/Docs/render.md) at how async postbacks are handled. Perhaps [this section](https://github.com/kjac/FormEditor/blob/master/Docs/render.md#performing-asynchronous-postback-with-the-noscript-rendering) would be of use.

However you'll probably encounter a CSRF issue with this. And also, that API is more or less specifically designed for form submission. So maybe you should check out the implementation of the API and try replicating that in a dedicated API of your own?

**Comment by bob-2165** [comment]
Ok, thanks. I'll look into it. I'm also trying to implement the form which is unique for each customer who logs in to the website. So customer logs in > fills out form > form populates a word document > customer logs out (hopefully).

Any suggestions regarding: (1) what service to use to populate a word document but to ensure that any parsing is highly encrypted to ensure data protection of very sensitive information, and (2) would form editor work for custom urls unique to each customer if they login, or instead of having a customer user login to the website, instead provide them with a unique expiring url that allows only the holder of that url to fill out the form (to avoid the public from filling out information in that form if they come across that url for whatever reason)?

**Comment by kjac** [comment]
Good luck!

Have a look at [the docs](https://github.com/kjac/FormEditor/blob/master/Docs/reuse.md) concerning reusable forms if you want the same form available for multiple users. Otherwise I guess you just need to create pages with forms for those unique URLs and that'd be it.
