### ISSUE TITLE
Cant seem to auto-fill more than 2 fields.

### ISSUE THREAD

**Issue by kieron** [kjac/FormEditor#206]
Sorry this isnt strictly an 'issue' but im just using the package, and following [this](https://github.com/kjac/FormEditor/blob/master/Tutorials/DefaultValues.md), I was able to get Name + Email auto-filled, the same as the guide, but then I added a third one, seen here:

```
var formModel = Umbraco.TypedContent(1275).GetPropertyValue<FormModel>("form");
                    var allValueFields = formModel.AllValueFields();
                    
                    var field = allValueFields.FirstOrDefault(f => "name".Equals(f.Name, StringComparison.OrdinalIgnoreCase));
                    if(field != null && field.HasSubmittedValue == false)
                    {
                    field.SetSubmittedValue(userName, Model.Content);
                    }
                    
                    field = allValueFields.FirstOrDefault(f => "email".Equals(f.Name, StringComparison.OrdinalIgnoreCase));
                    if(field != null && field.HasSubmittedValue == false)
                    {
                    field.SetSubmittedValue(userEmail, Model.Content);
                    }
                    
                    var field = allValueFields.FirstOrDefault(f => "manager".Equals(f.manager, StringComparison.OrdinalIgnoreCase));
                    if(field != null && field.HasSubmittedValue == false)
                    {
                    field.SetSubmittedValue(userManager, Model.Content);
                    }
```

I also have in the Form content, a text-field, called [Manager](https://gyazo.com/e408ad723209b7523593890ee365feb9), where I have tried uppercase, lowercase, space with an extra word etc, but I keep receiving this error; [pic here also](https://gyazo.com/01a2790cca1b7ee17f860727370b5ed0)

```
 var field = allValueFields.FirstOrDefault(f => "manager".Equals(f.manager, StringComparison.OrdinalIgnoreCase));
Line 81:                     if(field != null && field.HasSubmittedValue == false)
Line 82:                     {
```

Thanks in advance!

I have tried naming the field different things and changing the code but just cant seem to get it to go.

**Comment by kjac** [comment]
Hi... I see a few errors in your code.

1. You can't declare `var field` twice. 
2. `f` does not have a `manager` property. You're looking for the `Name` property when you do that kind of comparison. That's why the name and email fields both work.
