### ISSUE TITLE
Security Issue?

### ISSUE THREAD

**Issue by bob-2165** [kjac/FormEditor#207]
Hi there,

I have received 3 contact form requests through this form from what appears to be a spam bot indicating some type of ransomwear: 

"Hey. Soon your hosting account and your domain [website] will be blocked forever, and you will receive tens of thousands of negative feedback from angry people. 

Here is a list of what you get if you don’t follow my requirements: 
+ abuse spamhouse for aggressive web spam 
+ tens of thousands of negative reviews about you and your website from angry people for aggressive web and email spam 
+ lifetime blocking of your hosting account for aggressive web and email spam 
+ lifetime blocking"

Is there any security concern regarding the contact form?

**Comment by kjac** [comment]
Hi there. Well, reCAPTCHA is supported out of the box. It's really good for spam protection on your forms.

Read more about it [in the docs](https://github.com/kjac/FormEditor/blob/master/Docs/fields.md#the-recaptcha-fields).

**Comment by bob-2165** [comment]
Hi, it looks like it got through reCAPTCHA. I am just trying to assess the potential security risk if they inject some type of code into the form to spam the website. I found a few examples of this on the internet.
