### ISSUE TITLE
Multiple forms issues

### ISSUE THREAD

**Issue by ragivi** [kjac/FormEditor#21]
Hello!

First of all thank you for your work, it's an excellent plugin and each version is more impressive.

It was to talk to you about a couple of things about the integration of multiple forms:

- The validation of required fields interferes between forms. For example, if I fill out the form 1 and try it to submit, if I have a required field on the form 2 show the validator of the form 2.
- Moreover, if I have one form on the top of the page and the other at the end, I don't know how make it work.

Regards.

**Comment by kjac** [comment]
Hey @ragivi,

Currently there's no support for multiple forms on the same page. It's one of those things I'm tinkering with - the most recent UI overhaul is actually the first step towards this.

**Comment by ragivi** [comment]
Hi,

Ok, I figured it. Thanks!!

**Comment by kjac** [comment]
This is in part solved in version 0.14.1.1. 

For the time being there are no plans for supporting multiple forms on the same document type.
