### ISSUE TITLE
Form editor for umbraco 8

### ISSUE THREAD

**Issue by MastuaCR** [kjac/FormEditor#215]
Is it possible to get a version of this project available for umbraco 8+? Or is there an easy way to make the forms created in umbraco 7.14 with formEditor running on umbraco 8?

**Comment by kjac** [comment]
Hi @MastuaCR,

There are currently no plans of porting this to V8+ ... and I doubt there's any easy way to make a quick fix that will allow the V7 forms to work on V8.
