### ISSUE TITLE
Multiple pages with the same form

### ISSUE THREAD

**Issue by ragivi** [kjac/FormEditor#27]
Hi!

It has happened to me that I have in multiple pages the same form, so I have to create the form on every page where I want it to appear.

My question is, is there any way to create a single form and reference it on multiple pages once?

I guess that the solution is create another View (duplicating FormEditorSync.cshtml) and change the var form to obtain it by a NodeId, but I can't make it work:

`var form = Model.Content.GetPropertyValue<FormModel>("form");`

Thanks!

**Comment by kjac** [comment]
Hi @ragivi,

You can do this quite easily - no need to create the same form everywhere :)

It's all documented [here](https://github.com/kjac/FormEditor/blob/master/Docs/reuse.md).

**Comment by ragivi** [comment]
Great!

It was just what I wanted.

Thanks!

**Comment by kjac** [comment]
@ragivi glad I could help :)
