### ISSUE TITLE
Forms editor gives error after save and publish

### ISSUE THREAD

**Issue by KalpeshDave7883** [kjac/FormEditor#34]
Hi,

I am totally new in umbraco, so may be its my mistake to not identify the error or properly not set the FomsEditor.
This is really very useful and great tool for me. but when I did every thing and just save and publish it. Then go for the preview the form I got one error for assembly.

![image](https://cloud.githubusercontent.com/assets/19710580/15747064/b9caa4d4-28f6-11e6-9493-f336fe4083d5.png)

please assist me if I am doing any mistake.

Thanks in advance :)

**Comment by KalpeshDave7883** [comment]
Can you please tell me why I get this error?

**Comment by kjac** [comment]
Hi there.

It looks like there's a problem in your template - it's referring a view model that does not seem to exist.

Can you get your form rendered if you use one of the sample templates as described [here](https://github.com/kjac/FormEditor/blob/master/Docs/render.md)?

**Comment by KalpeshDave7883** [comment]
Hi ,

I had tried your sample forms also but not get success. Can you please look at the url ?
Where i have installed the package for it.

Url: umbracodev2.brnd.com\umbraco
User: brndadmin
Pass: qhfxGJet

Its very needful for me to get this work. Please help me to come out of this


Thanks for your help
Kalpesh


Sent from Samsung Mobile



-------- Original message --------

**Comment by kjac** [comment]
Hey.

I've tried applying the sample template to your contact form (http://umbracodev2.brnd.com/contact-form/) and it works just fine. So something is wrong with your FormEditor2 template. 

It looks to me like it's referencing a non-existing view model in the `UmbracoTemplatePage<>` inheritance. Maybe the ModelsBuilder needs to rebuild your doctype models - that could be one explanation. But you'll have to take this to Umbraco as it's not a FormEditor related problem.

Good luck!

-Kenn

**Comment by KalpeshDave7883** [comment]
thank you very much sir, I got the problem now :)
