### ISSUE TITLE
hi,

### ISSUE THREAD

**Issue by KalpeshDave7883** [kjac/FormEditor#37]
hi,

I am using formeditor and now I just want to fit it with our CSS that we are using material CSS. I have tried to remove the boot strap CSS from sample form and tried to give our own CSS to have consistency in project. 

![image](https://cloud.githubusercontent.com/assets/19710580/15816336/efc1c850-2bef-11e6-99f6-a6ecdd32a560.png)

but as you see in the screen shot it will always take bootstrap css from some where. i already have removed the things from the cshtml file and make its layout on standerd master page that we have

![image](https://cloud.githubusercontent.com/assets/19710580/15816399/3f761b6c-2bf0-11e6-8b7e-44ff30ed23f2.png)

can you please let me know that is there any other place in umbraco where I have to change the things?

thanks in advance for your help

**Comment by kjac** [comment]
Hi @KalpeshDave7883,

FormEditor itself doesn't load any CSS - only the template can do that. If you've commented out the link as you've shown above, and Bootstrap still loads, you must have a reference to it elsewhere in your template hierarchy.

-Kenn

**Comment by KalpeshDave7883** [comment]
There is no link is given in my project for boot strap, as I told you its only material design. And I am also able to change in DataType of the formeditor but on the cell.alias in template its always render with the older class like class="col-md-6" which I have already changed to class="col m6" as you shown in my screen dump I sent. :)

**Comment by kjac** [comment]
OK, I think I understand your problem now. 

The row and cell aliases are saved within the FormEditor property value. If you've changed the aliases in the datatype setup after building your form, you'll have to rebuild the form to get the new aliases.

**Comment by KalpeshDave7883** [comment]
Genius! sir I am just been you big friend.. 

I am also thinking to add one more property to all the fields like 2 dropdowns which of one just contains the values of each entity name from MSCRM and the other can give the result of all the columns of that entity from MSCRM.. 

also this to be mandatory fields to be chosen by user, cause off course it needs to be mapped with the forms fields.. so while submitting the data from 3rd user it will save the data to the fields in MSCRM and also we can track the data on submission tab like you have done already.. 

Will give you update if I will be success then it will be a great achievement :)
