### ISSUE TITLE
template gives error

### ISSUE THREAD

**Issue by KalpeshDave7883** [kjac/FormEditor#38]
Hi,

sorry to write you always for small things, as I am new in umbraco and my first task is more then complex given by leaders then any umbraco new comers.

As the things is running very well with your sample files but if I tried to do the same for the other template with same code copy and paste then I am not able to get the things work.. and it always gives me same error 

![image](https://cloud.githubusercontent.com/assets/19710580/15818152/4a2694d4-2bf9-11e6-89f2-24f5bb630ccb.png)

can you please tell me where I am wrong? or miss any config file to add entry?

**Comment by kjac** [comment]
It looks like the `form` variable is null. You're probably retrieving it by the wrong name or from the the wrong IPublishedContent.

**Comment by KalpeshDave7883** [comment]
Thanks Sir
