### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by ragivi** [kjac/FormEditor#4]
Hello,

First of all, congratulate you for the package, is very good and I found it very useful.

I've used it in various projects and I've thought these improvements, if you want to take them into account:

- Support to placeholder attribute. I've solved this by extending the fields, but I think it could be very easy and useful if the package got it natively.
- Being able to have more than one form in the same url. I've solved this by creating a form in code and post the values to other form in another url.

Regards!

**Comment by kjac** [comment]
Hey @ragivi ,

Thanks for the feedback. 

Placeholder attributes are on the way. Hopefully the next release is not far off. It will be awesome :)

Having more than one form on the same URL is sort of supported out of the box, but you can't have more than one form on the same piece of Umbraco content. I'll see if I can make time to document how to do it.

**Comment by ragivi** [comment]
Thanks @kjac,

I'm really excited with the arrival of the new version! :D

Ok, I stay pending wing documentation of multiple forms.

Thank you and congratulations again for your work.

**Comment by kjac** [comment]
Decided to release the placeholder labels and a fix for #5 right away. You can get it @ https://github.com/kjac/FormEditor/releases/tag/v0.10.0.2-beta
