### ISSUE TITLE
Storing data on SQL not working probably 

### ISSUE THREAD

**Issue by rasmusfjord** [kjac/FormEditor#41]
Or maybe a more correct title "Im probably doing it wrong".

So i want it to use SQL for storage so i have set my formeditor.config file to :
```
  <Storage>
     <Index type="FormEditor.SqlIndex.Storage.Index, FormEditor.SqlIndex" />
  </Storage>
```

But when i save a form it still creates the indexes in App_Data, and if i remove the form/index folder(ex. "1206") the data for the form is gone. Am i missing something

**Comment by kjac** [comment]
Hey @rasmusfjord,

Did you build the [SQL index](https://github.com/kjac/FormEditor/tree/master/Samples/SQL%20storage%20index) from the samples and did you include it in your /bin folder? It definitively sounds like it's missing... :)

**Comment by rasmusfjord** [comment]
Oh :) No, thought the sql it self was part of the core. That is prob. what im missing. Sec will try.

**Comment by rasmusfjord** [comment]
ARH now it works :) 

Sorry it was not clear to me that i had to build it and add it by my self :) Thx for an awesome job and see cya at CG16 !

**Comment by kjac** [comment]
Cool 😎 see you at CG!
