### ISSUE TITLE
FormEditorApi controller not found.

### ISSUE THREAD

**Issue by eriksimonic** [kjac/FormEditor#46]
Hi. I have installed the latest version from NuGet, and installed it on Umbraco 7.4.3

In the backoffice a get /umbraco/backoffice/FormEditorApi/PropertyEditor/GetAllConditionTypes 404, for all Api call to the /umbraco/backoffice/FormEditorApi

Do you have any idea?

**Comment by kjac** [comment]
Hey @eriksimonic,

That's weird. Do you see FormEditor.dll in your /bin-folder?

**Comment by eriksimonic** [comment]
Yes. It is in the bin directory

**Comment by eriksimonic** [comment]
If i run the application in x64 bit the FormEditor works.. only in may local IIS was a bit troublesome.
So for now I am testing the functionality, it works even trought an Macro witch is great, I can create a reusable form. 

I am only missing a Workflow setup, I know that you have a event on witch I can hook may custom logic, But it would be realy neet to have a Workflow interface  "IFormEditorWorkflow", and you could just create a new class and when the data is saved, the workflow is called with the whole model and formdata.. so I could have different processing paths for different forms.. for now we have only 2x options.. and is a bit limiting. 

BTW.. did I mention that is quite a nice extension!

**Comment by kjac** [comment]
Hey @eriksimonic :)

I'm glad you solved it. I'm a bit puzzled, though... I just installed a fresh Umbraco 7.4.3 with the latest FormEditor (0.13.3.2), all from NuGet, and ran it on IISExpress with no trouble at all. FormEditor isn't built specifically for x64, as far as I know. So... strange.

With respect to workflow - I'd love to hear your ideas, if you have something concrete?

**Comment by eriksimonic** [comment]
Hi.

The workflows or plugable runtimes or something like this.
I would implement it like this.

In the property editor I would add a new tab, Custum Actions
There I could select a custom developed class that implements and interface ie IFormEditorAction, 

public class FormEditorActionParamater
{
 public string propertyAlias {get;set;}
public string propertyName {get;set;}
public Bool Required {get;set;}
public object Value {get;set;}
public string BaseType {get;set;}
}
public class FormEditorActionParameters
{
  public class FormEditorActionParamater  Parameters  {get;set;}
}

public interface IFormEditorAction 
{
 void Execute(ref Dictionary<string,object> postedValues, IPublishedContent formContentNode, EditForm formDefinition);
string ActionName {get;}
FormEditorActionParameters ActionParameters {get;}
}

With this construct it would be posible to populate custum action required parameters, when the action is selected, and with a search for instance of we could find all avalable action classes.. 

Does make it any sense?
