### ISSUE TITLE
Backed hover over icon, icon disappears.

### ISSUE THREAD

**Issue by eriksimonic** [kjac/FormEditor#49]
In the property editor  Submissions tab, if you hover over an icon, it despairs.. so it looks a bit jurkej.. 
Version 0.14.04
Google Chrome Version 51.0.2704.103 m

Regards.

![image](https://cloud.githubusercontent.com/assets/10416737/17325057/cb15f9a4-58a9-11e6-81b9-bfbd7d30a522.png)

**Comment by kjac** [comment]
Hi @eriksimonic,

I can't reproduce this - it looks fine both on my local dev install and on a production install. Maybe you need to clear cache or something?

![hover](https://cloud.githubusercontent.com/assets/7405322/17340955/bf08f050-58f2-11e6-82ff-41055a24de6c.png)

**Comment by eriksimonic** [comment]
@kjac 
It is still present after cache refresh.
Confirmed IE and Chrome
Check this video if it helps.
http://youtu.be/ABaBVID2Y2U?hd=1

**Comment by kjac** [comment]
@eriksimonic I can reproduce now. Thanks :) I'll make sure it's fixed asap.

**Comment by eriksimonic** [comment]
@kjac Thanks, it is an annoyance.. but anything else :) But my editors will be pleased that the submissions grid is not blinking anymore :)

**Comment by kjac** [comment]
@eriksimonic Oh but it definitively needs fixing :) thanks for being so patient with me finding it. Turns out it's a 7.4.3 style that's been added and I was testing on 7.4.1

**Comment by eriksimonic** [comment]
@kjac  no problem I really like the extension as it gives a lot of flexibility. So it is worth some time investment.
