### ISSUE TITLE
rowId in AfterAddToIndex Event

### ISSUE THREAD

**Issue by alecrt** [kjac/FormEditor#5]
Hi kjac,

impressive work. I'm playing with your code and it's as simple as extensible.
Just one question: i need to pass the persisted rowId to an external CRM application.

But on AfterAddToIndex  event the rowId in not exposed by the the form model.
Could you plz add it?

Thanks,
Alessandro

**Comment by kjac** [comment]
Hey @alecrt,

Sure thing. Makes sense.

Your PR #6 has reformatted the entire FormModel class, so I won't merge it in as-is. Instead I'll close it and re-implement your solution asap.

**Comment by kjac** [comment]
Closed via #7

**Comment by kjac** [comment]
Its ready for all your CRM integration joy :)

https://github.com/kjac/FormEditor/releases/tag/v0.10.0.2-beta

**Comment by alecrt** [comment]
Great, already up and running ;)

Thx m8

**Comment by ragivi** [comment]
Great job!! Thanks.
