### ISSUE TITLE
Wrong behavior when submitting file attachment.

### ISSUE THREAD

**Issue by eriksimonic** [kjac/FormEditor#50]
When submitting a form with an attachment field, and it is configured to send attachments by email, the attachment is empty. 
See the screen shot.

![image](https://cloud.githubusercontent.com/assets/10416737/17325898/6086721c-58ae-11e6-9f67-8b48f7955a5e.png)

**Comment by kjac** [comment]
@eriksimonic Strange... that used to work :smile: 

I'll test and get back to you.

**Comment by kjac** [comment]
Hi @eriksimonic,

I just tested attaching uploaded images to the notification email and it works fine when sending the mail to Mailtrap. Are you sure it's not your mail server that's giving you a hard time?

![image upload](https://cloud.githubusercontent.com/assets/7405322/17340827/258b7c18-58f2-11e6-9d4c-c9c51494152f.png)

**Comment by eriksimonic** [comment]
@kjac  I will try to run it trough a debugger.

**Comment by kjac** [comment]
@eriksimonic Fair point - I'll add that to the next release :+1:
