### ISSUE TITLE
Add an option to override showHideValidationErrorForField

### ISSUE THREAD

**Issue by eriksimonic** [kjac/FormEditor#57]
Hi I had to override how classes are added to the controls. I did expose this function in the Sync library so it can be overridden. It may be useful for others to.

https://github.com/eriksimonic/FormEditor/blob/master/Source/Umbraco/JS/FormEditor/FormEditorSync.js

Regards
Erik

**Comment by kjac** [comment]
Hey @eriksimonic,

Nice. I'll test it out as soon as I can and merge it :)

Thanks!
