### ISSUE TITLE
Readme.md ToC links directing to /kjac/Docs/ instead of /kjac/FormEditor/Docs/

### ISSUE THREAD

**Issue by BarryGibson** [kjac/FormEditor#59]
Hi Kenn,

The links on github in the Table of contents aren't currently working they are redirecting you to 
https://github.com/kjac/Docs/
instead of
https://github.com/kjac/FormEditor/Docs/

**Comment by kjac** [comment]
Hey @BarryGibson .... that's annoying. I'll fix it asap :) thanks!

**Comment by kjac** [comment]
@BarryGibson it may be a bug in GitHub... the links should work according to https://help.github.com/articles/relative-links-in-readmes/ (and they used to work). I'll wait a bit and see if something magically fixes the links :)

**Comment by BarryGibson** [comment]
Yes they were working last week so maybe a GitHub issue.

**Comment by BarryGibson** [comment]
Working this morning (Something magically happened)

**Comment by kjac** [comment]
@BarryGibson Yeah... I talked to GitHub support and they did something magic :smile: 

Once again, thanks for reporting the issue! :+1:
