### ISSUE TITLE
Feature Request: Edit forms

### ISSUE THREAD

**Issue by BarryGibson** [kjac/FormEditor#62]
Hi, Have you considered the ability to edit submitted forms at all.
I'm currently putting something together to list the records and and then allow the user to edit. 
Is this type of functionality something that you have thought about or looked into, any input would be appreciated and welcome.

**Comment by kjac** [comment]
Hi @BarryGibson,

At the moment the indexes do not support updates. I considered it as a feature from backend, but it's not easily accomplished, as custom field types make editing non-deterministic.

Another problem is if the indexes were changed to support updates to existing form entries, any custom indexes out there would be broken. So it'd have to be exposed through an optional interface, like the statistics interface.

Off the top of my head I'm thinking:

1. Add update capability to the default index, implemented through an optional interface.
2. Edit the form entry in frontend using the form editor rendering (somehow seeded with the form entry values).
3. Use the "before add to index" event to somehow tell FormEditor it's an update, not an insert.

Does it make sense?

**Comment by BarryGibson** [comment]
Hi @kjac,

Thanks for your response, it does make sense.
I am working on this currently so will let you know how I go.

Thanks again,

Barry

**Comment by BarryGibson** [comment]
Hi @kjac,

I have moved along and made some progress on this and would be interested in your feedback as to my approach before I clean it up a bit more and put in a pull request (if that is of interest). 

1. I went ahead with your steps above and implemented an optional interface and added to the default index. 
2. I seeded the data into the form entry by adding to the CollectSubmittedValues to also get values from the database if a RowId is passed in on the query string.
3. And finally before adding I checked if a RowId was passed in and if so I do and update instead of an add.

Also at this stage my Update is implemented as an AddorUpdate and I am considering whether I should rename or fix it (i.e. throw an error if the record doesn't exist to be updated)

The changes have been pushed to the EditForms Branch of my fork.

**Comment by kjac** [comment]
Hey @BarryGibson :)

Kudos for taking this on! 👍 

I just had a quick look and you're definitively on the right track. I will have to download your branch and have a proper look, hopefully tonight. 

One thing I think you should revisit is the way you seed the `FormModel`. In my opinion you should expose a `LoadValues(Guid rowId)` method, that would seed the `FormModel` explicitly. You could set the `RowId` property here, and subsequently use it to determine whether to do an update or an insert in `CollectSubmittedValues()`. 

The flow would look something like this:

```cs
@{
  var rowId = Guid.Parse(/*something from the querystring? */);
  var form = Model.Content.GetPropertyValue<FormModel>("form");
  // first seed the form model with the existing values and the corresponding row ID
  form.LoadValues(rowId);
  // then collect and handle the new values (if it's a POST) - this will trigger an update
  form.CollectSubmittedValues();
}

<form>
  @* render the form model with the seeded values (or the collected values, e.g. in case of validation errors) */
</form>
```

I hope that made sense 😄

**Comment by BarryGibson** [comment]
Thanks @kjac, 

I've taken on board your feedback and agree it's a better way to seed the `FormModel`.
I have made the changes to my branch, and look forward to any further feedback.

**Comment by kjac** [comment]
Hey @BarryGibson,

I think the flow looks good. This is definitively something we need in the project. 

There are some things in the form data access and statistics that I'd like to try out and maybe suggest some changes to, but first thing's first: 

Does it work for you?

If so I'd like to create a branch that you can create a PR of the current changes into. Then I'll give it a spin this weekend and see what I can come up with.

**Comment by BarryGibson** [comment]
Hi @kjac,

Yes it works for me. I am currently using it with a SQL index. (haven't had time yet to check the default index or much experience with Lucene).

Would be happy to do a push request into a branch you set-up.

**Comment by kjac** [comment]
@BarryGibson cool :) I'm sure we can make this a great feature. 

If you'll make a PR to the edit-form-data branch I'll merge it in and start tinkering with it.

**Comment by kjac** [comment]
@BarryGibson I've made a few changes to your code in the edit-form-data branch - simplified some of it a bit and added some reuse in the index. Could you please pull it when you have time and see if it works for you?

As I've noted in the `IUpdateIndex` interface, I believe it should be merged with the generel `IIndex` interface in a few releases, which will further reduce the complexity of doing updates.

**Comment by BarryGibson** [comment]
@kjac Thanks very much, I have pulled it and it seems to be working well.

I like your simplifications and agree with the merging of the `IUpdateIndex` interface into the general `IIndex` interface when appropriate.

Also thanks for fixing up and improving the performance with my hack on the Default index. 👍

**Comment by kjac** [comment]
@BarryGibson Cool, I'll get it merged in asap then. And thank you for doing all the hard work 👍

**Comment by kjac** [comment]
@BarryGibson The new release is out - thanks again for the effort 👍
