### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by eriksimonic** [kjac/FormEditor#64]
Hi.

I have come across an scenario where it would be a fantastic thing, that an editor could change/add class names of the row.

I have an really advanced form implementation and it is really difficult to edit because I have to create new row and move all elements to that tow, just to apply an style to that row. 

I hope it make some sense..

**Comment by kjac** [comment]
Hey @eriksimonic :)

How about just restyling your existing row (by alias), instead of migrating/moving all your existing fields to a new row type?

**Comment by eriksimonic** [comment]
@kjac 
It should suffice.

**Comment by kjac** [comment]
@eriksimonic Cool.

I may be overthinking your scenario here. But... sometimes you may find yourself in a situation where you have e.g. an existing "One column" row that you want to split into two variants - say... "One column advanced" and "One column". Best way to do this without data loss is to rename the existing "One column" row to "One column advanced" without altering it's alias, and then create a new "One column" row with a different alias - e.g. "one-column-simple".

**Comment by kjac** [comment]
Closing this now :)

**Comment by eriksimonic** [comment]
You to clearly my intent here.. 
Still it would be a nice feature to have as I have to implement a form that needs to be something ultra fantastic as the design team come up. In this case it would really help a lot that you could specify a css class fro the containing row. For now I have separate rows that do the same thins 2x colum design.. 

as i every part of grid editing there is an option to add custom css class on that specific row so you can design it... I hope you understand, but it is a quite an annoyance. 

When the site lunches I will share the implementation to see. 
Regards.

**Comment by kjac** [comment]
@eriksimonic I think I misunderstood your request then :smile: 

If I understand you correctly you want to be able to specify a style sheet on the Form Editor data type, which should be loaded into the backoffice, and be able to target specific rows and cells in this style sheet?

**Comment by eriksimonic** [comment]
@kjac Yes. This is correct. Right now we have a hard time to style the form .

**Comment by kjac** [comment]
@eriksimonic Alrighty! I'll get right on that, shouldn't be any kind of troublesome to make.

**Comment by kjac** [comment]
@eriksimonic Ready in the new release :)

**Comment by eriksimonic** [comment]
@kjac Dam.. I really suck when I have to explain something.

This is the feature that we would need. The custom style is no problem at all.. 
![image](https://cloud.githubusercontent.com/assets/10416737/19072125/c7cdcf4a-8a33-11e6-9668-be44aae6e9bb.png)

**Comment by kjac** [comment]
@eriksimonic Hmmm... why can't you target your row using the row alias CSS class name? Is it the same row type?

**Comment by eriksimonic** [comment]
@kjac  Hi.

Yes the row layout is always the same, but the rows are styles bit different for each data segment. For now we have something like this.. as you imagine. it is a bit messy.

![image](https://cloud.githubusercontent.com/assets/10416737/19110928/2ba0f3a2-8afd-11e6-91f2-f2938a4d03b4.png)

As far I am concerned a row and a cell should have an option to add a custom css class name, so it is easy to target its content with JS or CSS.

In those forms we have to show hide segments based by checkbox name.. we solved this with naming convention 

example.. not perfect but it works well 
checkbox name : [name]_toggle
row alias [name as checkbox]_toggle

**Comment by kjac** [comment]
@eriksimonic The idea with Form Editor is to have multiple row types (e.g. "One column simple", "One column highlighted" etc) and let the editors pick the ones they want. Using the row alias as CSS class in frontend you should then be able to target the row types individually. 

With the added backend CSS option you can now style the individual rows in a way so the editors can tell them apart. Does that make sense?

**Comment by eriksimonic** [comment]
@kjac no the additional css class name is used for the front end not the editor. So the fronted custom scripts and styles are easier applied. Right now if we have a 2 column layout and one column layout differ form the other just for an padding or .. an icon added to that row. we have to create a separate row definition.. in this case it is totally redundant .. to do that, as it is only needed to add a class name to that element so it could be styles for the fronted.

This is the same as in the GridEditor (umbraco) you can specify attributes that you can apply to specific element, rows columns and so on. As this is editor domain and website technical documentation it should be editable from the content part.

Thanks.
