### ISSUE TITLE
Malware removed by windows defender when installing FormEditor.Binaries nuget package

### ISSUE THREAD

**Issue by rocifier** [kjac/FormEditor#71]
Which file do I need to whitelist on Windows Defender (windows 10) to stop it removing one of the files when I install the FormEditor.Binaries package? Or can I just ignore that error?

**Comment by BarryGibson** [comment]
HI @rocifier what malware is Windows Defender identifying it as?

**Comment by rocifier** [comment]
I figured it out, it's identifying bin\ImageProcessor.Web.dll as Win32/Vundo.IB
I whitelisted the bin folder and it installed. But I still can't get it working. Do I still need FormEditor.Binaries  and does that library work across separate projects with mvc and another project for business logic?

**Comment by kjac** [comment]
@rocifier I can't figure out if you're doing an Umbraco project or not; Form Editor is for Umbraco only.

If you are, you should try to get Umbraco working first using the Umbraco NuGet package, then install Form Editor.

**Comment by BarryGibson** [comment]
@kjac and @rocifier, 

This appears to be an issue with ImageProcessor see:
[https://our.umbraco.org/forum/umbraco-7/developing-umbraco-7-packages/71929-umbraco-imageprocessorwebdll-is-appearing-as-a-trojan](https://our.umbraco.org/forum/umbraco-7/developing-umbraco-7-packages/71929-umbraco-imageprocessorwebdll-is-appearing-as-a-trojan)

I have also been experiencing it.

**Comment by kjac** [comment]
@BarryGibson Thanks. I've seen it every so often too, but so far I've had no problems arise from it in my development cycle.

**Comment by rocifier** [comment]
I've let all the devs in the office know about the false detection. We're pretty keen on working with this form editor. So far we've been using it successfully in a number of situations (all Umbraco projects) but what I've been trying to do today is create a custom control which houses a group of dynamically generated controls. However I've been unsuccessful so far in following the tutorial for creating custom controls. After following all the steps, the custom control (which is named uniquely and consistently across all files) is not showing up. I tried restarting the site many times and screwing around with the FormEditor.Binaries dependency. I finally ended up ditching that dependency since it was for .net 4.0 only, and just putting the source code into my solution and trying to build that and configure a gulp task to build the plugin js into form.js. However, that has still been unsuccessful. Am I completely not on the right track here?

**Comment by kjac** [comment]
@rocifier Cool. And I'm glad you like it :)

It does sounds like you're in a pickle with your custom field, though. From what I can tell, you're making a lot of things very difficult for yourself.

I think you should try downloading the [sample project] (https://github.com/kjac/FormEditor/tree/master/Samples/Advanced%20custom%20field) and use that as a basis for your own custom field. Mind you, you may need to downgrade the NuGet package version of FormEditor.Binaries in the project to align with your Umbraco project, because I try to keep the sample projects updated with the latest and greatest NuGet package versions.

**Comment by rocifier** [comment]
Hmm I'm not really sure what I've done.. I reverted back to a previous commit after getting javascript errors in the backend, but the javascript errors haven't gone away. Basically my project now just has the reference to FormEditor nuget package, but the javascript errors are still there even after rebuilding and restarting the site:

[http://imgur.com/a/jg1Hn](screenshot)

**Comment by rocifier** [comment]
Okay I got it working by enabling debug mode in web.config as described here: https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/63392-PackageManifest-doesnt-actually-load-the-javascript-files

Back to the drawing board now XD

**Comment by rocifier** [comment]
Ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh I found the missing step which wasn't in the tutorial: [http://imgur.com/a/CycCQ](screenshot of doctype). Everything is working now.

**Comment by kjac** [comment]
@rocifier Cool :) I'm happy you got things working! I'll add a reminder to the tutorials to avoid any future issues like this.

**Comment by kjac** [comment]
The docs have been updated... I'm closing this now.
