### ISSUE TITLE
Can't enter more then one adders in recipient addresses!

### ISSUE THREAD

**Issue by eriksimonic** [kjac/FormEditor#73]
Hi this is urgent,
I can't enter more the one adders in the recipient address.

![image](https://cloud.githubusercontent.com/assets/10416737/19428375/0968d06a-944a-11e6-9ae1-71d78329f7b5.png)

![image](https://cloud.githubusercontent.com/assets/10416737/19428377/10bae38a-944a-11e6-9711-ffbf8c35a1d0.png)

**Comment by kjac** [comment]
@eriksimonic Snap! That's annoying... looks like Angular doesn't like multiple email addresses in one email field. I'll look at it.

If you need a quick fix right here and now, you can edit `\app_plugins\formeditor\editor\form.html` and change the input with ID `emailNotificationRecipients` from `type="email"` to `type="text"` - it *should* work. Keep in mind that you'll need to update your client dependency version (in `\Config\ClientDependency.config`) to bust the site cache.

**Comment by kjac** [comment]
@eriksimonic fixed in v0.15.1.4. 

Thanks for reporting 👍

**Comment by eriksimonic** [comment]
@kjac  Thanks for express fix.
