### ISSUE TITLE
Error  - FormEditor.SqlIndex.Storage.Index 

### ISSUE THREAD

**Issue by eriksimonic** [kjac/FormEditor#75]
I have undocumented the FormEditor.config line to enable SQLIndex, I get this error.
Am I missing something? Is this not included in the Core?

Could not load custom Index type (requested content ID: 4610)
System.Configuration.ConfigurationErrorsException: Custom Index type "FormEditor.SqlIndex.Storage.Index, FormEditor.SqlIndex" could not be found
   at FormEditor.Configuration.Load()

**Comment by eriksimonic** [comment]
@kjac 
Definitly, I would add a note to the documentation section...

**Comment by kjac** [comment]
Hey @eriksimonic,

It's in the docs already: https://github.com/kjac/FormEditor/blob/master/Docs/storage.md#changing-the-storage-index

But for clarity I'll add a note to FormEditor.config too :)
