### ISSUE TITLE
Email template accessing filed labels

### ISSUE THREAD

**Issue by eriksimonic** [kjac/FormEditor#78]
Hi.

How can I access filed label in the template.
I can access Name, PreatyName but not the label as it is displayed on he frontend. Thanks.

**Comment by eriksimonic** [comment]
Solved.

` var label = (FormEditor.Fields.FieldWithLabel)field;`

**Comment by kjac** [comment]
@eriksimonic correct 😄 

Remember though that not all value fields have labels (for example - the MemberInfo field does not). Consider something like this with a fallback to the field name:

```xml
<pre>Field label (or name): @(field is FormEditor.Fields.FieldWithLabel ? (field as FormEditor.Fields.FieldWithLabel).Label : field.Name)</pre>
```
