### ISSUE TITLE
Option to have number of submissions database driven

### ISSUE THREAD

**Issue by BarryGibson** [kjac/FormEditor#80]
Currently limiting the submissions per user is cookie based, however if the user clears their cookies or  uses another device they can submit again.
I know this is probably the best option for anonymous users however for known users (members) it would be useful to allow them to submit only once in a database driven fashion.

**Comment by kjac** [comment]
Hi @BarryGibson,

The cookie based solution is indeed the best solution I could come up with for anonymous users, and it's along the lines of how others handle it - for examle [Survey Monkey](http://help.surveymonkey.com/articles/en_US/kb/What-settings-allow-multiple-responses-from-one-computer).

I get where you're going with logged in members, but at least for the time being I don't see it implemented as part of the core. However, I'll have a look at facilitating a provider based solution so you can plug in your own system for keeping track of submission limitations per user.

For now you'll have to add your own solution [here](https://github.com/kjac/FormEditor/blob/d11768142e125dde16e53a40ea78c96815da7b46/Source/Umbraco/Views/Partials/FormEditor/Sync.cshtml#L32) (for synchronous form postback) or [here](https://github.com/kjac/FormEditor/blob/d11768142e125dde16e53a40ea78c96815da7b46/Source/Umbraco/Views/Partials/FormEditor/Async.cshtml#L27) (for asynchronous form postback).

-Kenn

**Comment by BarryGibson** [comment]
Thanks @kjac

**Comment by eriksimonic** [comment]
@kjac Hi I am intruding in a debate. Right now I had a scenario that we have to limit the submit to 1 but only for a specific time period (1h), I did roll may one solution with an AfterInset.. .but it may be more mainstream to include it in the form properties. What do you think? Regards.

**Comment by kjac** [comment]
Hey @eriksimonic, 

You're not intruding 😄 any and all input are welcome.

I think a provider based solution will work perfectly in your case as well. The benefit over using the events is that you can utilize the "Max submissions" title and text to give the end users a meaningful explanation, and it'll "just work" once you plug your own provider in.

I'll get to this soon, promise.

**Comment by kjac** [comment]
@BarryGibson @eriksimonic I published a new release with the provider based solution mentioned above - [read more here](https://github.com/kjac/FormEditor/blob/master/Docs/extend.md#custom-handling-of-submission-limitations).

You can replace the default handling with your own, either globally (by configuration) or per instance. 

You should probably consider basing your own handling on the default one (`MaxSubmissionsForCurrentUserHandler`) by simply extending it and overriding its methods. This way you can still use the cookie based handling for your anonymous users, and replace then handling with your own custom one for whenever you can identify your users.

Let me know how it works for you :)

**Comment by BarryGibson** [comment]
Thanks for your help @kjac

**Comment by kjac** [comment]
Closing this - the feature is documented [here](https://github.com/kjac/FormEditor/blob/master/Docs/extend.md#custom-handling-of-submission-limitations).
