### ISSUE TITLE
Feature: Additional option to reload users response when one submission per user is selected

### ISSUE THREAD

**Issue by BarryGibson** [kjac/FormEditor#81]
It would be good to be able to return the users current submission for them to edit as an option when Only one submission per user is selected.

Here is a screen shot of what I was thinking
![submissions](https://cloud.githubusercontent.com/assets/15335262/19618464/a7db9e76-9896-11e6-815a-b6b312b3033d.png)

**Comment by kjac** [comment]
Hey @BarryGibson,

There's no way of telling which submission was created by the current user, unless you have a `MemberInfo` field somewhere in the form. Thus I don't see this as a terribly mainstream requirement, sorry.

You can roll your own solution, though. If your storage index supports full text search (implements `IFullTextIndex` - the default one does), you can do a search into the index using the current member data ([see here](https://github.com/kjac/FormEditor/blob/057490a710407cc5a35af2f1e2398d6dd33c0df4/Source/Solution/FormEditor/Fields/MemberInfoField.cs#L31) for the search query format) and allow the member to edit the resulting row (if any).

**Comment by BarryGibson** [comment]
Thanks @kjac I have implemented my own solution at this stage. I agree it's not terribly mainstream, However I have a very member based solution, so am putting together a memberHelper to do this for my needs, and will share it once I have it working.
Also with the IFullTextIndex what is the standard for wildcards, I just want to make sure my implementation is compatible with the default one.

**Comment by kjac** [comment]
@BarryGibson sounds cool. 

I wouldn't worry too much about wildcard handling. Right now the full text search is only ever used when searching the submissions from backend, so whatever you think makes sense in that respect will work just fine. 

The default implementation uses leading wildcards and does not support trailing or mid-query ones.

**Comment by kjac** [comment]
@BarryGibson can this be closed now?

**Comment by BarryGibson** [comment]
@kjac thanks yes closing it now. I have started on my implementation and will let you know once I have it in a sharable format.

**Comment by kjac** [comment]
@BarryGibson nice, looking forward to that 👍
