### ISSUE TITLE
Question: Is it possible to set the receipt page to an external url

### ISSUE THREAD

**Issue by BarryGibson** [kjac/FormEditor#82]
Hi,
Is it possible to set the receipt page to an external url?

Thanks

**Comment by kjac** [comment]
@BarryGibson Hey... nope. It's an Umbraco page ID :)

But you can do your own redirect handling after collecting the submitted values, if you set the `redirect` paramter to `false`:
 
```cs
bool CollectSubmittedValues(IPublishedContent content, bool redirect = true)
```

...the method returns `true` if the form was submitted.
