### ISSUE TITLE
Question reload listing on async postback

### ISSUE THREAD

**Issue by BarryGibson** [kjac/FormEditor#85]
Hi @kjac, 
I was hoping for a little advice, I have setup something similar to you recent rating tutorial, but want to refresh the listing following a submission. (my solution is a bit like a todo list) Also the users are allowed to submit multiple submissions, so I need clear the form so they can add a new record. Any tips or suggestion where to look would be greatly appreciated, I am new to angular and trying to nut it out.

Thanks

Barry

**Comment by kjac** [comment]
Hey @BarryGibson,

For security reasons there's no public endpoint that allows fetching submissions, so you'll have to write your own. 

Then have a look at the Angular docs for $http to bind your view to your endpoint.

There should be plenty of docs for Form Editor on how to access the submissions serverside 😄

**Comment by kjac** [comment]
@BarryGibson I'm closing this. I hope you got what you needed to progress on your implementation.
