### ISSUE TITLE
Attaching files does not work.

### ISSUE THREAD

**Issue by eriksimonic** [kjac/FormEditor#86]
Hi I have this configuration, and I can confirm that the form editor does not attach the files to the notification email.

![image](https://cloud.githubusercontent.com/assets/10416737/19644475/4316d446-99f0-11e6-9681-efd6e92e44e0.png)

![image](https://cloud.githubusercontent.com/assets/10416737/19644471/3ef3b9f6-99f0-11e6-9f9e-13d689f2f757.png)

![image](https://cloud.githubusercontent.com/assets/10416737/19644535/8e0bdce4-99f0-11e6-8282-6e9491f1c092.png)

Version 0.15.2.1
Regards!

**Comment by eriksimonic** [comment]
@kjac Maybe. . I will check! asap.
Thank you for super fast response.

**Comment by eriksimonic** [comment]
@kjac 
Hi I tracked down the error to this point that the ContentLaneght of the file is reseted to 0 after it is added to the index, I am using SQLIndex from your examples. I guess something went bananas here.. 
I will try to debug it..

**Comment by kjac** [comment]
@eriksimonic I will have a look at the sample SQL index as soon as I can find the time. Thanks for reporting it 👍

**Comment by kjac** [comment]
@eriksimonic If you get the latest SQL index from the samples section, it should work.

I've patched FormModel too in an attempt to avoid similar issues with other custom indexes, but you don't need to be concerned about it - the changes to the SQL index should suffice.
