### ISSUE TITLE
May I Use Your Storage Code?

### ISSUE THREAD

**Issue by Nicholas-Westby** [kjac/FormEditor#87]
Hi Kenn,

I made Formulate, which is similar to your form editor. I noticed your form editor has support to store submissions: https://github.com/kjac/FormEditor/blob/master/Docs/storage.md

I am planning to add support for this to Formulate. My hope was that I can use some of your code to help speed up the process of adding support for storage of submissions. **Would that be OK with you?**

If so, I would be happy to add a link to your project from the "Thanks" section here: https://github.com/rhythmagency/formulate

By the way, I couldn't find a forum to submit questions to, so I hope this is the right place to do so.

-Nick

**Comment by kjac** [comment]
Hi @Nicholas-Westby,

Sure you can 😄  Form Editor is open source, and as long as you keep Formulate open source as well, I have no problem with that. 

A link would of course be appreciated.

I'd also appreciate if you'd refrain from copying the form submission statistics. It's one of the things that set Form Editor apart, and I'd like to keep it that way. Of course I can't tell you not to copy it, as it is all open source, so I'll stick with asking nicely.

-Kenn

**Comment by Nicholas-Westby** [comment]
Much appreciated! And will do, I'll keep my grubby hands off of the statistics features 😄
