### ISSUE TITLE
Question: is FormEditor using jquery.validate?

### ISSUE THREAD

**Issue by BarryGibson** [kjac/FormEditor#90]
Hi @kjac,

Does FormEditor use Jquery.validate? I am getting some javascript errors caused by a unknown in jquery.validate, I have this on my master because some of my other stuff uses it and I think its putting its nose in where it shouldn't be. I can't see any reference to FormEditor using it so was going to do some refactoring so it wouldn't be referenced on the form pages but wanted to check if it's supposed to be being referenced and used?

Thanks

Barry

**Comment by kjac** [comment]
Hey there, @BarryGibson.

No it shouldn't. The validation in `FormEditorSync.js` is based on the validation state of the input fields (`input.validity`).

I think the easiest way to figure out if it is Form Editor or not is to simply remove your reference to `FormEditorSync.js` and see if you still get the error?

**Comment by BarryGibson** [comment]
Thanks @kjac,

I found the issue and it wasn't Form Editor, thanks for your help.
