### ISSUE TITLE
Dates not showing submitted value from saved record

### ISSUE THREAD

**Issue by BarryGibson** [kjac/FormEditor#91]
Hi,

When you re-display a form that has a date field it doesn't show the date.

To solve this, I have overidden the SubmittedValue in the DateField.cs file:
```
public override string SubmittedValue
{
	get
	{
		DateTime submittedValue;
		if(DateTime.TryParse(base.SubmittedValue, out submittedValue))
		{
			return submittedValue.ToString("yyyy-MM-dd");
		}
		return base.SubmittedValue;
	}
	protected set
	{
		base.SubmittedValue = value;
	}
}
```

I'm not sure if this is your prefered approach, but I thought I would share my problem and solution.

**Comment by kjac** [comment]
Hey @BarryGibson,

Thank you for reporting and for the suggested fix.

It looks like there's an issue with async submission of dates - they append time/timezone info. It's an angular thing that's easily fixable, but before I fix it, I need to know one thing... how do the submitted dates look in your backend? Without your applied fix, that is.

**Comment by BarryGibson** [comment]
Hi @kjac, 

Here is an example:
2016-11-02T13:00:00.000Z

I think you are correct, because the ones collected through a different Sync version of the form don't include the time info.

Thanks

Barry

**Comment by kjac** [comment]
Cool, apparently it's a feature in angularjs...

I'll have a fix ready soon, today hopefully.

**Comment by kjac** [comment]
@BarryGibson it's fixed... I'll roll out a release soon.
