### ISSUE TITLE
SPAM prevention without reCAPTCHA. (Suggestion)

### ISSUE THREAD

**Issue by eriksimonic** [kjac/FormEditor#94]
Hi.

Just a suggestion. 

We had a nice spam filtering mechanism in place on our former site. The spam protection worked like this.
on the form add 2x new hidden fields, 

on post you need to validate the fields like that
first field should be empty
second field must be date time (is encrypted ) with at least 5seconds offset. With this method we complety blocked bot submissions. 

Regards.

**Comment by kjac** [comment]
@eriksimonic Thanks for the input. It's an interesting.

How did you fill in the second field on the client?

**Comment by eriksimonic** [comment]
@kjac 
It should be empty.. I am currently trying to create a custom field to do this thing.. but I would really need 2x fields.. not an array. 

<input type="hidden" name="@(Model.FormSafeName)[]" value=" "/>

![image](https://cloud.githubusercontent.com/assets/10416737/20298403/04514f3e-ab16-11e6-9f5e-8629085a06bb.png)

for the Encrytion I do use MachineKey.Protect. .net 4+

**Comment by kjac** [comment]
Hi @eriksimonic,

It should absolutely be doable to implement this as a custom field by implementing `IFieldWithValidation` - have a look at the ReCaptcha field implementation for inspiration. 

In `CollectSubmittedValue` you'll get all the submitted form values passed as `allSubmittedValues`, so if your field always renders two hidden form fields (e.g. _prevent_sub_1 and _prevent_sub_2), you can look for them in `CollectSubmittedValue` and then evaluate them in `ValidateSubmittedValue`.

**Comment by eriksimonic** [comment]
@kjac 
Great I will look at this.
You can close this if you think this is not needed in the core.

I can share the code when is done?

Regards.

**Comment by kjac** [comment]
@eriksimonic Sure, I'd like to see the result. Maybe it makes sense to add it to the core :)

**Comment by kjac** [comment]
I'm closing this due to lack of updates.
