### ISSUE TITLE
Dispose of SmtpClient

### ISSUE THREAD

**Issue by Nicholas-Westby** [kjac/FormEditor#95]
I noticed you are creating an SMTP client here: https://github.com/kjac/FormEditor/blob/0df7ac67fead06e04b77bbd3fd9dfdb1317102f7/Source/Solution/FormEditor/FormModel.cs#L700

Looks like you aren't creating it with a "using" statement, so it may not be disposed of in a timely manner. That can be lead to periodic email send failures.

This same issue existed in the Umbraco core. You can read about the details here: http://issues.umbraco.org/issue/U4-6504

I can create a pull request if you like, but it should just be a quick fix.

**Comment by kjac** [comment]
Thanks @Nicholas-Westby 👍 

I'll fix it asap. Of course you're more than welcome to submit a PR if you want to.

**Comment by Nicholas-Westby** [comment]
Here you go: https://github.com/kjac/FormEditor/pull/96

**Comment by kjac** [comment]
Cool. I'll prepare for a new release soon!

**Comment by kjac** [comment]
@Nicholas-Westby ...and it's released. Thanks again 👍
