### ISSUE TITLE
Feature Request: Duplicate Question

### ISSUE THREAD

**Issue by BarryGibson** [kjac/FormEditor#97]
It would be great to be able to duplicate a question and then change the text, this would be especially helpful when creating multiple question with the same options.

**Comment by kjac** [comment]
@BarryGibson when you say duplicate a question... do you mean duplicate a field? Or field options for multi value fields?

**Comment by BarryGibson** [comment]
@kjac I meant duplicating a field.
However I have also been thinking about how to create a shared set of field options.

**Comment by kjac** [comment]
@BarryGibson cool. I've been wanting to implement field duplication for some time, so I'll have a look at it.

**Comment by kjac** [comment]
@BarryGibson fixed by #99 and just released 😄

**Comment by BarryGibson** [comment]
@kjac, Amazing thanks for the quick release 👍 😄
