### ISSUE TITLE
Feature request: Grid Question type for radiobutton / checkbox questions

### ISSUE THREAD

**Issue by BarryGibson** [kjac/FormEditor#98]
It would be great to have a grid question type for radio buttons and check boxes, this question type would allow multiple questions to be stored against the same set of options and would have the questions layed out in a grid, something like the image below:
![image](https://cloud.githubusercontent.com/assets/15335262/20738833/491fa7e6-b70a-11e6-8fad-31870f562a62.png)

**Comment by kjac** [comment]
@BarryGibson this kind of field should probably be built as a custom field. 

I'm considering starting up a separate project for custom fields and other useful extensions, that can't be in the core... this field type could be meaningful to add there.

**Comment by BarryGibson** [comment]
Hi @kjac I think that's a great idea, and I would be very happy to contribute to it. I am currently working on this field type. as well as a couple of others.

**Comment by kjac** [comment]
I've found no time to start a side project for custom fields and other extensions. If anyone's up for the task, by all means do so. 

I'm closing this for the time being.
